package dlt.dltbackendmaster.reports.queries;

/**
 * Consultas feitas na view
 * 
 * @author Hamilton Mutaquiha
 *
 */
public class AgywPrevQueries {

	public static final String AGYW_PREV = "select id, beneficiary_id, nui, current_age, date_of_birth, district_id, vblt_is_student, vblt_sexually_active, date_created, \n"
			+ "                    if(current_age = 15  and min(datediff(service_date,date_of_birth)/30) between 120 and 177,1,"
			+ "							if(current_age = 20  and min(datediff(service_date,date_of_birth)/30) between 180 and 237,2,current_age_band)) current_age_band,\n"
			+ "                    if(current_age < 20 and vblt_house_Sustainer=1,1,0) +\n"
			+ "                    if(current_age < 18 and vblt_is_student=0,1,0) +\n"
			+ "                    if(vblt_is_deficient=1,1,0) +\n"
			+ "                    if(current_age < 20 and vblt_married_before=1,1,0) +\n"
			+ "                    if(current_age < 20 and vblt_pregnant_before=1,1,0) +\n"
			+ "                    if(current_age < 20 and vblt_children=1,1,0) +\n"
			+ "                    if(current_age < 18 and vblt_pregnant_or_breastfeeding=1,1,0) +\n"
			+ "                    if(current_age < 18 and vblt_is_orphan=1,1,0) +\n"
			+ "                    if(vblt_tested_hiv < 2 and date_created < '2022-01-01',1,0) +\n"
			+ "                    if(vblt_sexual_exploitation=1,1,0) +\n"
			+ "                    if(current_age < 20 and vblt_is_migrant=1,1,0) +\n"
			+ "                    if(current_age < 20 and vblt_trafficking_victim=1,1,0) +\n"
			+ "                    if(current_age < 18 and vblt_sexually_active=1,1,0) +\n"
			+ "                    if(vblt_multiple_partners=1,1,0) +\n"
			+ "                    if(vblt_gbv_victim=1,1,0) +\n"
			+ "                    if(current_age > 17 and vblt_sex_worker=1,1,0) +\n"
			+ "                    if(vblt_alcohol_drugs_use=1,1,0) +\n"
			+ "                    if(vblt_sti_history=1,1,0) vulnerabilities, \n" 
			+ "                    sum(case\n"
			+ "                    when (vblt_is_student=1 and sub_service_id in (169,170,176,184,185,186,187,188,189,190,191,192,193,194,195,207,208,209)\n"
			+ "                        or vblt_is_student=0 and sub_service_id in (164,179,180,181,182,183,196,197,198,199,200)) then 1\n"
			+ "                    else 0\n" 
			+ "                    end) mandatory_social_assets,\n"
			+ "                    sum(case\n"
			+ "                        when (vblt_is_student=1 and sub_service_id in (165,166,167,168,171,172,173,174,175)\n"
			+ "                            or vblt_is_student=0 and sub_service_id in (157,158,159,160,161,162,163)) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) other_social_assets,\n"
			+ "                    sum(case\n"
			+ "                        when sub_service_id in (130,131,132,133,134,135,136,137,138,139,140,141,142,143,144) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) old_social_assets,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (77,88,89,90) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) saaj_educational_sessions,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (26,67,68) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) hiv_testing,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id = 215 then 1\n"
			+ "                        else 0\n" 
			+ "                    end) financial_literacy,\n"
			+ "                    sum(case\n"
			+ "                        when sub_service_id in (2,52,107,108) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) condoms,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (4,5,6,7,96) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) contraception,\n"
			+ "                    sum(case\n"
			+ "                        when sub_service_id in (201,202,203,204,205,206,210,211,212) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) hiv_gbv_sessions,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (216) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) hiv_gbv_sessions_prep,\n"
			+ "                    sum(case\n"
			+ "                        when sub_service_id in (112,114,115,116,117,118,119,120,121,122,123,124,125,126) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) hiv_sessions,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (113) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) gbv_sessions,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (35,36,37) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) school_allowance,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (9) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) post_violence_care_us,\n"
			+ "                    sum(case\n"
			+ "                        when sub_service_id in (8,10,11,12,13,14,97,150) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) post_violence_care_us_others,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (127) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) post_violence_care_comunity,\n"
			+ "                    sum(case\n"
			+ "                        when sub_service_id in (128,145,146,147,148) then 1\n"
			+ "                        else 0\n"
			+ "                    end) post_violence_care_comunity_others,\n" 
			+ "                    sum(case\n"
			+ "                        when sub_service_id in (69,70,71,72,73,74,75,92,93,95,109,110,111,151) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) other_saaj_services,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (177,178) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) social_assets_15_plus,\n"
			+ "                    sum(case\n"
			+ "                        when sub_service_id in (40,82,83,84,85,86,87,214,235) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) social_economics_approaches,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (214,235) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) disag_social_economics_approaches,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id = 156 then 1\n"
			+ "                        else 0\n" 
			+ "                    end) prep,\n" 
			+ "                    sum(case\n"
			+ "                        when sub_service_id in (196,197,198,199,200) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) girl_violence_prevention,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (207,208,209) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) student_vilence_prevention,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (210,211,212) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) violence_prevention_15_plus,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (217,218,219,220,221,222,223) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) financial_literacy_aflatoun,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (224,225,226,227,228,229,230,231,232) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) financial_literacy_aflateen,\n"
			+ "                    min(service_date) intervention_date,\n" 
			+ "                    max(case\n"
			+ "                        when sub_service_id in (214) then service_date\n"
			+ "                    end) approaches_date,"
			+ "					   if(enrollment_date is null, min(service_date), enrollment_date) enrollment_date\n" 
			+ "				from agyw_prev_mview\n"
			+ "				where district_id in (:districts) "
			+ "				and vulnerable = 1 "
			+ "				and current_age_band <> 5 "
			+ "				and nui <> '' "
			+ "				and service_date is not null "
			+ "				and service_date <> '' "
			+ "				and service_date between '2000-01-01' and :end\n"
			+ "				and beneficiary_id in"
			+ "				(\n"
			+ "					select distinct beneficiary_id  \n"
			+ "					from agyw_prev_mview\n"
			+ "					where service_date between :start and :end\n"
			+ "					and intervention_status=1\n" 
			+ "				) \n"
			+ "				group by beneficiary_id, district_id, current_age_band, vblt_is_student, vblt_sexually_active, date_created, vulnerabilities";

	public static final String SIMPLIFIED_AGYW_PREV = "select id, beneficiary_id, nui, current_age, date_of_birth, district_id, vblt_is_student, vblt_sexually_active, date_created, \n"
			+ "                    if(current_age = 15  and min(datediff(service_date,date_of_birth)/30) between 120 and 177,1,"
			+ "							if(current_age = 20  and min(datediff(service_date,date_of_birth)/30) between 180 and 237,2,current_age_band)) current_age_band,\n"
			+ "                    if(current_age < 20 and vblt_house_Sustainer=1,1,0) +\n"
			+ "                    if(current_age < 18 and vblt_is_student=0,1,0) +\n"
			+ "                    if(vblt_is_deficient=1,1,0) +\n"
			+ "                    if(current_age < 20 and vblt_married_before=1,1,0) +\n"
			+ "                    if(current_age < 20 and vblt_pregnant_before=1,1,0) +\n"
			+ "                    if(current_age < 20 and vblt_children=1,1,0) +\n"
			+ "                    if(current_age < 18 and vblt_pregnant_or_breastfeeding=1,1,0) +\n"
			+ "                    if(current_age < 18 and vblt_is_orphan=1,1,0) +\n"
			+ "                    if(vblt_tested_hiv < 2 and date_created < '2022-01-01',1,0) +\n"
			+ "                    if(vblt_sexual_exploitation=1,1,0) +\n"
			+ "                    if(current_age < 20 and vblt_is_migrant=1,1,0) +\n"
			+ "                    if(current_age < 20 and vblt_trafficking_victim=1,1,0) +\n"
			+ "                    if(current_age < 18 and vblt_sexually_active=1,1,0) +\n"
			+ "                    if(vblt_multiple_partners=1,1,0) +\n"
			+ "                    if(vblt_gbv_victim=1,1,0) +\n"
			+ "                    if(current_age > 17 and vblt_sex_worker=1,1,0) +\n"
			+ "                    if(vblt_alcohol_drugs_use=1,1,0) +\n"
			+ "                    if(vblt_sti_history=1,1,0) vulnerabilities, \n" 
			+ "                    sum(case\n"
			+ "                    when sub_service_id in (162,179,181,182,183,196,198,199,200) then 1\n"
			+ "                    else 0\n" 
			+ "                    end) mandatory_social_assets,\n"
			+ "                    sum(case\n"
			+ "                        when sub_service_id in (157,158,159,160,161,162,163) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) other_social_assets,\n"
			+ "                    sum(case\n"
			+ "                        when sub_service_id in (130,131,132,133,134,135,136,137,138,139,140,141,142,143,144) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) old_social_assets,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (77,91) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) saaj_educational_sessions,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (26,67,68) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) hiv_testing,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id = 215 then 1\n"
			+ "                        else 0\n" 
			+ "                    end) financial_literacy,\n"
			+ "                    sum(case\n"
			+ "                        when sub_service_id in (2,52,107,108) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) condoms,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (4,5,6,7,96) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) contraception,\n"
			+ "                    sum(case\n"
			+ "                        when sub_service_id in (201,202,203,204,205,206,210,212) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) hiv_gbv_sessions,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (216) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) hiv_gbv_sessions_prep,\n"
			+ "                    sum(case\n"
			+ "                        when sub_service_id in (112,114,115,116,117,118,119,120,121,122,123,124,125,126) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) hiv_sessions,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (113) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) gbv_sessions,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (35,36,37) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) school_allowance,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (9) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) post_violence_care_us,\n"
			+ "                    sum(case\n"
			+ "                        when sub_service_id in (8,10,11,12,13,14,97,150) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) post_violence_care_us_others,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (147) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) post_violence_care_comunity,\n"
			+ "                    sum(case\n"
			+ "                        when sub_service_id in (127,128,145,146,148) then 1\n"
			+ "                        else 0\n"
			+ "                    end) post_violence_care_comunity_others,\n" 
			+ "                    sum(case\n"
			+ "                        when sub_service_id in (69,70,71,72,73,74,75,92,93,95,109,110,111,151) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) other_saaj_services,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (177,178) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) social_assets_15_plus,\n"
			+ "                    sum(case\n"
			+ "                        when sub_service_id in (40,82,83,84,85,86,87,214,235) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) social_economics_approaches,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (214,235) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) disag_social_economics_approaches,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id = 156 then 1\n"
			+ "                        else 0\n" 
			+ "                    end) prep,\n" 
			+ "                    sum(case\n"
			+ "                        when sub_service_id in (196,197,198,199,200) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) girl_violence_prevention,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (207,208,209) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) student_vilence_prevention,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (210,211,212) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) violence_prevention_15_plus,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (217,218,219,220,221,222,223) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) financial_literacy_aflatoun,\n"
			+ "                    sum(case\n" 
			+ "                        when sub_service_id in (224,226) then 1\n"
			+ "                        else 0\n" 
			+ "                    end) financial_literacy_aflateen,\n"
			+ "                    min(service_date) intervention_date,\n" 
			+ "                    max(case\n"
			+ "                        when sub_service_id in (214) then service_date\n"
			+ "                    end) approaches_date,"
			+ "					   if(enrollment_date is null, min(service_date), enrollment_date) enrollment_date\n" 
			+ "				from agyw_prev_mview\n"
			+ "				where district_id in (:districts) "
			+ "				and vulnerable = 1 "
			+ "				and current_age_band <> 5 "
			+ "				and nui <> '' "
			+ "				and service_date is not null "
			+ "				and service_date <> '' "
			+ "				and service_date between '2000-01-01' and :end\n"
			+ "				and beneficiary_id in"
			+ "				(\n"
			+ "					select distinct beneficiary_id  \n"
			+ "					from agyw_prev_mview\n"
			+ "					where service_date between :start and :end\n"
			+ "					and intervention_status=1\n" 
			+ "				) \n"
			+ "				group by beneficiary_id, district_id, current_age_band, vblt_is_student, vblt_sexually_active, date_created, vulnerabilities";
		
	public static final String NEWLY_ENROLLED_AGYW_AND_SERVICES= ""
			+ "select  provincia,\n"
			+ "	distrito,\n"
			+ "	onde_mora,\n"
			+ "	ponto_entrada,\n"
			+ "	organizacao,\n"
			+ "	data_inscricao,\n"
			+ "	data_registo,\n"
			+ "	registado_por,\n"
			+ "	data_actualizacao,\n"
			+ "	actualizado_por,\n"
			+ "	nui,\n"
			+ "	sexo,\n"
			+ "	idade_registo,\n"
			+ "	idade_actual,\n"
			+ "	faixa_registo,\n"
			+ "	faixa_actual,\n"
			+ "	data_nascimento,\n"
			+ "	-- data_nascimento_formatada,\n"
			+ "	if(agyw_prev=1,'Sim','Não') agyw_prev,\n"
			+ "	com_quem_mora,\n"
			+ "	sustenta_casa,\n"
			+ "	e_orfa,\n"
			+ "	vai_escola,\n"
			+ "	tem_deficiencia,\n"
			+ "	tipo_deficiencia,\n"
			+ "	foi_casada,\n"
			+ "	esteve_gravida,\n"
			+ "	tem_filhos,\n"
			+ "	gravida_amamentar,\n"
			+ "	trabalha,\n"
			+ "	teste_hiv,\n"
			+ "	area_servico,\n"
			+ "	a.servico,\n"
			+ "	sub_servico,\n"
			+ "	pacote_servico,\n"
			+ "	ponto_entrada_servico,\n"
			+ "	localizacao,\n"
			+ "	data_servico,\n"
			+ "	provedor,\n"
			+ "	observacoes,\n"
			+ "	servico_status\n"
			+ "from\n"
			+ "(\n"
			+ "	select distinct pr.name provincia,\n"
			+ "		dt.name distrito,\n"
			+ "		n.name onde_mora,\n"
			+ "		if(v.entry_point=1,'US',if(v.entry_point=2,'CM','ES')) ponto_entrada,\n"
			+ "		pa.name organizacao,\n"
			+ "		v.enrollment_date data_inscricao,\n"
			+ "		v.date_created data_registo,\n"
			+ "		u.name registado_por,\n"
			+ "		v.date_updated data_actualizacao,\n"
			+ "		u1.name actualizado_por,\n"
			+ "		v.nui,\n"
			+ "		if(v.gender=1,'M','F') sexo,\n"
			+ "		v.registration_age idade_registo,\n"
			+ "		v.current_age idade_actual,\n"
			+ "		if(v.registration_age_band=1,'9-14', if(v.registration_age_band=2,'15-19',if(v.registration_age_band=3,'20-24',if(v.registration_age_band=4,'25-29','')))) faixa_registo,\n"
			+ "		if(v.current_age_band=1,'9-14', if(v.current_age_band=2,'15-19',if(v.current_age_band=3,'20-24',if(v.current_age_band=4,'25-29','')))) faixa_actual,\n"
			+ "		v.date_of_birth data_nascimento,\n"
			+ "		-- STR_TO_DATE(v.data_nascimento,'%d/%m/%Y') data_nascimento_formatada,\n"
			+ "		if (v.gender = 2 and v.current_age > 8\n"
			+ "			and((v.vblt_tested_hiv is not null and v.vblt_tested_hiv < 2 and v.date_created < :endDate)\n"
			+ "			or v.vblt_multiple_partners = 1 \n"
			+ "			or v.vblt_is_deficient = 1\n"
			+ "			or v.vblt_gbv_victim = 1\n"
			+ "			or v.vblt_alcohol_drugs_use = 1\n"
			+ "			or v.vblt_sti_history = 1\n"
			+ "			or v.vblt_sexual_exploitation = 1 \n"
			+ "			or ((v.vblt_house_sustainer = 1 or v.vblt_married_before = 1 or v.vblt_pregnant_before = 1 or v.vblt_children = 1 or v.vblt_trafficking_victim = 1 or v.vblt_is_migrant = 1) and v.current_age < 20)\n"
			+ "			or ((v.vblt_sexually_active = 1 or v.vblt_pregnant_or_breastfeeding = 1 or v.vblt_is_student = 0 or (v.vblt_is_employed is not null and v.vblt_is_employed <> 0) or v.vblt_is_orphan=1) and v.current_age < 18)\n"
			+ "			or (v.vblt_sex_worker = 1 and v.current_age > 17)),\n"
			+ "			1,0) agyw_prev,\n"
			+ "		v.vblt_lives_with com_quem_mora,\n"
			+ "		if(v.vblt_house_sustainer=0,'Não', if(v.vblt_house_sustainer=1,'Sim','')) sustenta_casa,\n"
			+ "		if(v.vblt_is_orphan=0,'Não', if(v.vblt_is_orphan=1,'Sim','')) e_orfa,\n"
			+ "		if(v.vblt_is_student=0,'Não', if(v.vblt_is_student=1,'Sim','')) vai_escola,\n"
			+ "		if(v.vblt_is_deficient=0,'Não', if(v.vblt_is_deficient=1,'Sim','')) tem_deficiencia,\n"
			+ "		v.vblt_deficiency_type tipo_deficiencia,\n"
			+ "		if(v.vblt_married_before=0,'Não', if(v.vblt_married_before=1,'Sim','')) foi_casada,\n"
			+ "		if(v.vblt_pregnant_before=0,'Não', if(v.vblt_pregnant_before=1,'Sim','')) esteve_gravida,\n"
			+ "		if(v.vblt_children=0,'Não', if(v.vblt_children=1,'Sim','')) tem_filhos,\n"
			+ "		if(v.vblt_pregnant_or_breastfeeding=0,'Não', if(v.vblt_pregnant_or_breastfeeding=1,'Sim','')) gravida_amamentar,\n"
			+ "		if(v.vblt_is_employed=0,'Não', if(v.vblt_is_employed=1,'Empregada Doméstica',if(v.vblt_is_employed=2,'Babá (Cuida das Crianças)',if(v.vblt_is_employed=3,'Outros','')))) trabalha,\n"
			+ "		if(v.vblt_tested_hiv=0,'Não', if(v.vblt_tested_hiv=1,'Sim (+3 meses)',if(v.vblt_tested_hiv=2,'Sim (-3 meses)',''))) teste_hiv,\n"
			+ "	    if(v.service_type=1,'Clínico', 'Comunitário') area_servico,\n"
			+ "	    s.name servico,\n"
			+ "	    ss.name sub_servico,\n"
			+ "	    if(v.level=1,'Primário', if(v.level=2,'Secundário',if(v.level=3,'Conextual',if(v.level=4,'N/A',if(v.level=5,'Secundário (Primário se Sexualmente Activa)',''))))) pacote_servico,\n"
			+ "		if(v.entry_point=1,'US',if(v.entry_point=2,'CM','ES')) ponto_entrada_servico,\n"
			+ "		us.name localizacao,\n"
			+ "		v.service_date data_servico,\n"
			+ "		v.provider provedor,\n"
			+ "		v.remarks observacoes,\n"
			+ "		v.intervention_status servico_status\n"
			+ "	from agyw_prev_mview v\n"
			+ "	left join province pr on v.province_id = pr.id\n"
			+ "	left join district dt on v.district_id = dt.id\n"
			+ "	left join neighborhood n on v.neighborhood_id = n.id\n"
			+ "	left join partners pa on v.organization_id = pa.id\n"
			+ "	-- left join app_dream_tipo_servicos ts on v.area_servico_id = ts.id\n"
			+ "	left join services s on v.service_id = s.id\n"
			+ "	left join sub_services ss on v.sub_service_id = ss.id\n"
			+ "	-- left join app_dream_nivel_intervensao ni on v.pacote_servico_id = ni.id\n"
			+ "	left join us on v.us_id = us.id\n"
			+ "	left join users u on v.created_by = u.id\n"
			+ "	left join users u1 on v.updated_by = u1.id\n"
			+ "	where v.date_created between :startDate and :endDate\n"
			+ "	-- and v.vulneravel=1\n"
			+ "	-- and pr.id in (10)\n"
			+ "	and dt.id in (:districts) \n"
			+ "	-- and dt.district_code not in (7,8,25,26) -- ZAMBEZIA\n"
			+ "	order by pr.name, dt.name, v.nui\n"
			+ ") a";
		
	public static final String NEWLY_ENROLLED_AGYW_AND_SERVICES_SUMMARY= ""
			+ "select provincia,\n"
			+ "	distrito,\n"
			+ "	nui, \n"
			+ "	idade_actual,\n"
			+ "	faixa_actual,\n"
			+ "	vulnerabilidades,\n"
			+ "	if(agyw_prev=1,'Sim','Não') agyw_prev,\n"
			+ "	sum(case\n"
			+ "			when pa.partner_type=1 then 1\n"
			+ "			else 0\n"
			+ "	end) referecias_clinico,\n"
			+ "	sum(case\n"
			+ "			when pa.partner_type=2 then 1\n"
			+ "			else 0\n"
			+ "	end) referecias_comunitario,\n"
			+ "	recursos_sociais,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_recursos_sociais,'%Y-%m-%d'),'%d/%m/%Y') data_recursos_sociais,\n"
			+ "	prevencao_hiv,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_prevencao_hiv,'%Y-%m-%d'),'%d/%m/%Y') data_prevencao_hiv,\n"
			+ "	prevencao_vgb,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_prevencao_vgb,'%Y-%m-%d'),'%d/%m/%Y') data_prevencao_vgb,\n"
			+ "	educativas,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_educativas,'%Y-%m-%d'),'%d/%m/%Y') data_educativas,\n"
			+ "	literacia_financeira,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_literacia_financeira,'%Y-%m-%d'),'%d/%m/%Y') data_literacia_financeira,\n"
			+ "	ats,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_ats,'%Y-%m-%d'),'%d/%m/%Y') data_ats,\n"
			+ "	preservativos,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_preservativos,'%Y-%m-%d'),'%d/%m/%Y') data_preservativos,\n"
			+ "	contracepcao,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_contracepcao,'%Y-%m-%d'),'%d/%m/%Y') data_contracepcao,\n"
			+ "	abordagens_socio_economicas,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_abordagens_socio_economicas,'%Y-%m-%d'),'%d/%m/%Y') data_abordagens_socio_economicas,\n"
			+ "	subsidio_escolar,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_subsidio_escolar,'%Y-%m-%d'),'%d/%m/%Y') data_subsidio_escolar,\n"
			+ "	cuidados_pos_violencia_comunitarios,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_cuidados_pos_violencia_comunitarios,'%Y-%m-%d'),'%d/%m/%Y') data_cuidados_pos_violencia_comunitarios,\n"
			+ "	cuidados_pos_violencia_clinicos,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_cuidados_pos_violencia_clinicos,'%Y-%m-%d'),'%d/%m/%Y') data_cuidados_pos_violencia_clinicos,\n"
			+ "	outros_saaj,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_outros_saaj,'%Y-%m-%d'),'%d/%m/%Y') outros_saaj_date,\n"
			+ "	prep,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_prep,'%Y-%m-%d'),'%d/%m/%Y') data_prep\n"
			+ "from(	\n"
			+ "	select distinct v.beneficiary_id,\n"
			+ "		pr.name provincia,\n"
			+ "		dt.name distrito,\n"
			+ "		v.nui,\n"
			+ "		v.current_age idade_actual,\n"
			+ "		if(v.current_age_band=1,'9-14', if(v.current_age_band=2,'15-19',if(v.current_age_band=3,'20-24',if(v.current_age_band=4,'25-29','')))) faixa_actual,\n"
			+ "		v.date_of_birth data_nascimento,\n"
			+ "		if (v.gender = 2 and v.current_age > 8\n"
			+ "			and((v.vblt_tested_hiv is not null and v.vblt_tested_hiv < 2 and v.date_created < :endDate)\n"
			+ "			or v.vblt_multiple_partners = 1 \n"
			+ "			or v.vblt_is_deficient = 1\n"
			+ "			or v.vblt_gbv_victim = 1\n"
			+ "			or v.vblt_alcohol_drugs_use = 1\n"
			+ "			or v.vblt_sti_history = 1\n"
			+ "			or v.vblt_sexual_exploitation = 1 \n"
			+ "			or ((v.vblt_house_sustainer = 1 or v.vblt_married_before=1 or v.vblt_pregnant_before = 1 or v.vblt_children = 1 or v.vblt_trafficking_victim=1 or v.vblt_is_migrant = 1) and v.current_age < 20)\n"
			+ "			or ((v.vblt_sexually_active = 1 or v.vblt_pregnant_or_breastfeeding = 1 or v.vblt_is_student = 0 or (v.vblt_is_employed is not null and v.vblt_is_employed <> 0) or v.vblt_is_orphan=1) and v.current_age < 18)\n"
			+ "			or (v.vblt_sex_worker = 1 and v.current_age > 17)),\n"
			+ "			1,0) agyw_prev,\n"
			+ "	    if(v.current_age < 20 and v.vblt_house_sustainer=1,1,0) +\n"
			+ "		if(v.current_age < 18 and v.vblt_is_orphan=1,1,0) +\n"
			+ "		if(v.current_age < 18 and v.vblt_is_student=0,1,0) +\n"
			+ "		if(v.vblt_is_deficient=1,1,0) +\n"
			+ "		if(v.current_age < 20 and v.vblt_married_before=1,1,0) +\n"
			+ "		if(v.current_age < 20 and v.vblt_pregnant_before=1,1,0) +\n"
			+ "		if(v.current_age < 20 and v.vblt_children=1,1,0) +\n"
			+ "		if(v.current_age < 18 and v.vblt_pregnant_or_breastfeeding=1,1,0) +\n"
			+ "		if(v.vblt_tested_hiv < 2 and v.date_created < :endDate,1,0) +\n"
			+ "		if(v.vblt_sexual_exploitation=1,1,0) +\n"
			+ "		if(v.current_age < 20 and vblt_is_migrant=1,1,0) +\n"
			+ "		if(v.current_age < 20 and v.vblt_trafficking_victim=1,1,0) +\n"
			+ "		if(v.current_age < 18 and v.vblt_sexually_active=1,1,0) +\n"
			+ "		if(v.vblt_multiple_partners=1,1,0) +\n"
			+ "		if(v.vblt_gbv_victim=1,1,0) +\n"
			+ "		if(v.current_age < 18 and v.vblt_is_employed<>0,1,0) +\n"
			+ "		if(v.current_age > 17 and v.vblt_sex_worker=1,1,0) +\n"
			+ "		if(v.vblt_alcohol_drugs_use=1,1,0) +\n"
			+ "		if(v.vblt_sti_history=1,1,0) as vulnerabilidades,\n"
			+ "		sum(case\n"
			+ "			when v.service_id in (20,44,45,46) then 1\n"
			+ "			else 0\n"
			+ "		end) recursos_sociais,\n"
			+ "		max(case\n"
			+ "			when v.service_id in (20,44,45,46) then max_data_servico\n"
			+ "		end) data_recursos_sociais,\n"
			+ "		sum(case\n"
			+ "			when v.service_id in (28,41,47,48,49) then 1\n"
			+ "			else 0\n"
			+ "		end) prevencao_hiv,\n"
			+ "		max(case\n"
			+ "			when v.service_id in (28,41,47,48,49) then max_data_servico\n"
			+ "		end) data_prevencao_hiv,\n"
			+ "		sum(case\n"
			+ "			when v.service_id in (43,50,51,52) then 1\n"
			+ "			else 0\n"
			+ "		end) prevencao_vgb,\n"
			+ "		max(case\n"
			+ "			when v.service_id in (43,50,51,52) then max_data_servico\n"
			+ "		end) data_prevencao_vgb,\n"
			+ "		sum(case\n"
			+ "			when v.service_id=37 then 1\n"
			+ "			else 0\n"
			+ "		end) educativas,\n"
			+ "		max(case\n"
			+ "			when v.service_id=37 then max_data_servico\n"
			+ "		end) data_educativas,\n"
			+ "		sum(case\n"
			+ "			when v.service_id in (55,56,57) then 1\n"
			+ "			else 0\n"
			+ "		end) literacia_financeira,\n"
			+ "		max(case\n"
			+ "			when v.service_id in (55,56,57) then max_data_servico\n"
			+ "		end) data_literacia_financeira,\n"
			+ "		sum(case\n"
			+ "			when v.service_id=9 then 1\n"
			+ "			else 0\n"
			+ "		end) ats,\n"
			+ "		max(case\n"
			+ "			when v.service_id=9 then max_data_servico\n"
			+ "		end) data_ats,\n"
			+ "		sum(case\n"
			+ "			when v.service_id=1 then 1\n"
			+ "			else 0\n"
			+ "		end) preservativos,\n"
			+ "		max(case\n"
			+ "			when v.service_id=1 then max_data_servico\n"
			+ "		end) data_preservativos,\n"
			+ "		sum(case\n"
			+ "			when v.service_id=2 then 1\n"
			+ "			else 0\n"
			+ "		end) contracepcao,\n"
			+ "		max(case\n"
			+ "			when v.service_id=2 then max_data_servico\n"
			+ "		end) data_contracepcao,\n"
			+ "		sum(case\n"
			+ "			when v.service_id=21 then 1\n"
			+ "			else 0\n"
			+ "		end) abordagens_socio_economicas,\n"
			+ "		max(case\n"
			+ "			when v.service_id=21 then max_data_servico\n"
			+ "		end) data_abordagens_socio_economicas,\n"
			+ "		sum(case\n"
			+ "			when v.service_id=18 then 1\n"
			+ "			else 0\n"
			+ "		end) subsidio_escolar,\n"
			+ "		max(case\n"
			+ "			when v.service_id=18 then max_data_servico\n"
			+ "		end) data_subsidio_escolar,\n"
			+ "		sum(case\n"
			+ "			when v.service_id=42 then 1\n"
			+ "			else 0\n"
			+ "		end) cuidados_pos_violencia_comunitarios,\n"
			+ "		max(case\n"
			+ "			when v.service_id=42 then max_data_servico\n"
			+ "		end) data_cuidados_pos_violencia_comunitarios,\n"
			+ "		sum(case\n"
			+ "			when v.service_id=3 then 1\n"
			+ "			else 0\n"
			+ "		end) cuidados_pos_violencia_clinicos,\n"
			+ "		max(case\n"
			+ "			when v.service_id=3 then max_data_servico\n"
			+ "		end) data_cuidados_pos_violencia_clinicos,\n"
			+ "		sum(case\n"
			+ "			when v.service_id=36 then 1\n"
			+ "			else 0\n"
			+ "		end) outros_saaj,\n"
			+ "		max(case\n"
			+ "			when v.service_id=36 then max_data_servico\n"
			+ "		end) data_outros_saaj,\n"
			+ "		sum(case\n"
			+ "			when v.service_id=54 then 1\n"
			+ "			else 0\n"
			+ "		end) prep,\n"
			+ "		max(case\n"
			+ "			when v.service_id=54 then max_data_servico\n"
			+ "		end) data_prep\n"
			+ "	from agyw_prev_mview v\n"
			+ "	left join\n"
			+ "	(	select beneficiary_id, service_id, sub_service_id, max(service_date) max_data_servico\n"
			+ "		from agyw_prev_mview\n"
			+ "		where intervention_status=1\n"
			+ "		and district_id in (:districts) -- Distritos (18-Boane, 30-Ile)\n"
			+ "		group by beneficiary_id,service_id,sub_service_id\n"
			+ "	) servico on v.sub_service_id = servico.sub_service_id and v.beneficiary_id = servico.beneficiary_id\n"
			+ "	left join province pr on v.province_id = pr.id\n"
			+ "	left join district dt on v.district_id = dt.id\n"
			+ "	left join neighborhood n on v.neighborhood_id = n.id\n"
			+ "	left join partners pa on v.organization_id = pa.id\n"
			+ "	where v.date_created between :startDate and :endDate\n"
			+ "	-- and v.vulneravel=1\n"
			+ "	and dt.id in (:districts)\n"
			+ "	group by v.beneficiary_id\n"
			+ ") a\n"
			+ "left join dreams_db.references r on r.beneficiary_id=a.beneficiary_id and r.status=0\n"
			+ "LEFT JOIN users u ON r.user_created = u.id -- tabela de usuarios registados6\n"
			+ "LEFT JOIN partners pa ON u.partner_id = pa.id -- tabela de parceiros Dreams\n"
			+ "-- LEFT JOIN app_dream_parceiros_tipo pt ON pt.id=dp.parceria_id -- tabela por tipo de parceiro (CM/US/ES)\n"
			+ "group by a.beneficiary_id\n"
			+ "order by provincia,distrito,nui"	;
		
	public static final String VULNERABILITIES_AND_SERVICES=""
			+ "select  provincia,\n"
			+ "	distrito,\n"
			+ "	onde_mora,\n"
			+ "	ponto_entrada,\n"
			+ "	organizacao,\n"
			+ "	data_inscricao,\n"
			+ "	data_registo,\n"
			+ "	registado_por,\n"
			+ "	data_actualizacao,\n"
			+ "	actualizado_por,\n"
			+ "	nui,\n"
			+ "	sexo,\n"
			+ "	idade_registo,\n"
			+ "	idade_actual,\n"
			+ "	faixa_registo,\n"
			+ "	faixa_actual,\n"
			+ "	data_nascimento,\n"
			+ "	if(agyw_prev=1,'Sim','Não') agyw_prev,\n"
			+ "	com_quem_mora,\n"
			+ "	sustenta_casa,\n"
			+ "	e_orfa,\n"
			+ "	vai_escola,\n"
			+ "	tem_deficiencia,\n"
			+ "	tipo_deficiencia,\n"
			+ "	foi_casada,\n"
			+ "	esteve_gravida,\n"
			+ "	tem_filhos,\n"
			+ "	gravida_amamentar,\n"
			+ "	trabalha,\n"
			+ "	teste_hiv,\n"
			+ "	area_servico,\n"
			+ "	a.servico,\n"
			+ "	sub_servico,\n"
			+ "	pacote_servico,\n"
			+ "	ponto_entrada_servico,\n"
			+ "	localizacao,\n"
			+ "	data_servico,\n"
			+ "	provedor,\n"
			+ "	observacoes,\n"
			+ "	servico_status\n"
			+ "from\n"
			+ "(\n"
			+ "	select distinct pr.name provincia,\n"
			+ "		dt.name distrito,\n"
			+ "		n.name onde_mora,\n"
			+ "		if(v.entry_point=1,'US',if(v.entry_point=2,'CM','ES')) ponto_entrada,\n"
			+ "		pa.name organizacao,\n"
			+ "		v.date_created data_registo,\n"
			+ "		v.enrollment_date data_inscricao,\n"
			+ "		u.name registado_por,\n"
			+ "		v.date_updated data_actualizacao,\n"
			+ "		u1.name actualizado_por,\n"
			+ "		v.nui,\n"
			+ "		if(v.gender=1,'M','F') sexo,\n"
			+ "		v.registration_age idade_registo,\n"
			+ "		v.current_age idade_actual,\n"
			+ "		if(v.registration_age_band=1,'9-14', if(v.registration_age_band=2,'15-19',if(v.registration_age_band=3,'20-24',if(v.registration_age_band=4,'25-29','')))) faixa_registo,\n"
			+ "		if(v.current_age_band=1,'9-14', if(v.current_age_band=2,'15-19',if(v.current_age_band=3,'20-24',if(v.current_age_band=4,'25-29','')))) faixa_actual,\n"
			+ "		v.date_of_birth data_nascimento,\n"
			+ "		if (v.gender = 2 and v.current_age > 8\n"
			+ "			and((v.vblt_tested_hiv is not null and v.vblt_tested_hiv < 2 and v.date_created < :endDate)\n"
			+ "			or v.vblt_multiple_partners = 1 \n"
			+ "			or v.vblt_is_deficient = 1\n"
			+ "			or v.vblt_gbv_victim = 1\n"
			+ "			or v.vblt_alcohol_drugs_use = 1\n"
			+ "			or v.vblt_sti_history = 1\n"
			+ "			or v.vblt_sexual_exploitation = 1 \n"
			+ "			or ((v.vblt_house_sustainer = 1 or v.vblt_married_before = 1 or v.vblt_pregnant_before = 1 or v.vblt_children = 1 or v.vblt_trafficking_victim = 1 or v.vblt_is_migrant = 1) and v.current_age < 20)\n"
			+ "			or ((v.vblt_sexually_active = 1 or v.vblt_pregnant_or_breastfeeding = 1 or v.vblt_is_student = 0 or (v.vblt_is_employed is not null and v.vblt_is_employed <> 0) or v.vblt_is_orphan=1) and v.current_age < 18)\n"
			+ "			or (v.vblt_sex_worker = 1 and v.current_age > 17)),\n"
			+ "			1,0) agyw_prev,\n"
			+ "		v.vblt_lives_with com_quem_mora,\n"
			+ "		if(v.vblt_house_sustainer=0,'Não', if(v.vblt_house_sustainer=1,'Sim','')) sustenta_casa,\n"
			+ "		if(v.vblt_is_orphan=0,'Não', if(v.vblt_is_orphan=1,'Sim','')) e_orfa,\n"
			+ "		if(v.vblt_is_student=0,'Não', if(v.vblt_is_student=1,'Sim','')) vai_escola,\n"
			+ "		if(v.vblt_is_deficient=0,'Não', if(v.vblt_is_deficient=1,'Sim','')) tem_deficiencia,\n"
			+ "		v.vblt_deficiency_type tipo_deficiencia,\n"
			+ "		if(v.vblt_married_before=0,'Não', if(v.vblt_married_before=1,'Sim','')) foi_casada,\n"
			+ "		if(v.vblt_pregnant_before=0,'Não', if(v.vblt_pregnant_before=1,'Sim','')) esteve_gravida,\n"
			+ "		if(v.vblt_children=0,'Não', if(v.vblt_children=1,'Sim','')) tem_filhos,\n"
			+ "		if(v.vblt_pregnant_or_breastfeeding=0,'Não', if(v.vblt_pregnant_or_breastfeeding=1,'Sim','')) gravida_amamentar,\n"
			+ "		if(v.vblt_is_employed=0,'Não', if(v.vblt_is_employed=1,'Empregada Doméstica',if(v.vblt_is_employed=2,'Babá (Cuida das Crianças)',if(v.vblt_is_employed=3,'Outros','')))) trabalha,\n"
			+ "		if(v.vblt_tested_hiv=0,'Não', if(v.vblt_tested_hiv=1,'Sim (+3 meses)',if(v.vblt_tested_hiv=2,'Sim (-3 meses)',''))) teste_hiv,\n"
			+ "	     if(v.service_type=1,'Clínico', 'Comunitário') area_servico,\n"
			+ "	     s.name servico,\n"
			+ "	     ss.name sub_servico,\n"
			+ "	     if(v.level=1,'Primário', if(v.level=2,'Secundário',if(v.level=3,'Conextual',if(v.level=4,'N/A',if(v.level=5,'Secundário (Primário se Sexualmente Activa)',''))))) pacote_servico,\n"
			+ "		if(v.entry_point=1,'US',if(v.entry_point=2,'CM','ES')) ponto_entrada_servico,\n"
			+ "		us.name localizacao,\n"
			+ "		v.service_date data_servico,\n"
			+ "		v.provider provedor,\n"
			+ "		v.remarks observacoes,\n"
			+ "		v.intervention_status servico_status\n"
			+ "	from\n"
			+ "	(\n"
			+ "		select beneficiary_id,max(service_date)\n"
			+ "		from agyw_prev_mview\n"
			+ "		where service_date between :startDate and :endDate		\n"
			+ "		and intervention_status = 1\n"
			+ "		group by beneficiary_id\n"
			+ "	) servico_ano\n"
			+ "	left join agyw_prev_mview v on servico_ano.beneficiary_id=v.beneficiary_id\n"
			+ "	left join province pr on v.province_id = pr.id\n"
			+ "	left join district dt on v.district_id = dt.id\n"
			+ "	left join neighborhood n on v.neighborhood_id = n.id\n"
			+ "	left join partners pa on v.organization_id = pa.id\n"
			+ "-- 	left join app_dream_tipo_servicos ts on v.area_servico_id = ts.id\n"
			+ "	left join services s on v.service_id = s.id\n"
			+ "	left join sub_services ss on v.sub_service_id = ss.id\n"
			+ "	-- left join app_dream_nivel_intervensao ni on v.pacote_servico_id = ni.id\n"
			+ "	left join us on v.us_id = us.id\n"
			+ "	left join users u on v.created_by = u.id\n"
			+ "	left join users u1 on v.updated_by = u1.id\n"
			+ "	where v.service_date <= :endDate\n"
			+ "	-- and v.vulneravel=1\n"
			+ "	-- and pr.id in (2,8)\n"
			+ "	and dt.id in (:districts)\n"
			+ "	order by pr.name, dt.name, nui\n"
			+ ") a";
	public static final String VULNERABILITIES_AND_SERVICES_SUMMARY=""
			+ "select provincia,\n"
			+ "	distrito,\n"
			+ "	nui, \n"
			+ "	idade_actual,\n"
			+ "	faixa_actual,\n"
			+ "	vulnerabilidades,\n"
			+ "	if(agyw_prev=1,'Sim','Não') agyw_prev,\n"
			+ "	sum(case\n"
			+ "			when pa.partner_type=1 then 1\n"
			+ "			else 0\n"
			+ "	end) referecias_clinico,\n"
			+ "	sum(case\n"
			+ "			when pa.partner_type=2 then 1\n"
			+ "			else 0\n"
			+ "	end) referecias_comunitario,\n"
			+ "	recursos_sociais,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_recursos_sociais,'%Y-%m-%d'),'%d/%m/%Y') data_recursos_sociais,\n"
			+ "	prevencao_hiv,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_prevencao_hiv,'%Y-%m-%d'),'%d/%m/%Y') data_prevencao_hiv,\n"
			+ "	prevencao_vgb,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_prevencao_vgb,'%Y-%m-%d'),'%d/%m/%Y') data_prevencao_vgb,\n"
			+ "	educativas,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_educativas,'%Y-%m-%d'),'%d/%m/%Y') data_educativas,\n"
			+ "	literacia_financeira,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_literacia_financeira,'%Y-%m-%d'),'%d/%m/%Y') data_literacia_financeira,\n"
			+ "	ats,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_ats,'%Y-%m-%d'),'%d/%m/%Y') data_ats,\n"
			+ "	preservativos,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_preservativos,'%Y-%m-%d'),'%d/%m/%Y') data_preservativos,\n"
			+ "	contracepcao,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_contracepcao,'%Y-%m-%d'),'%d/%m/%Y') data_contracepcao,\n"
			+ "	abordagens_socio_economicas,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_abordagens_socio_economicas,'%Y-%m-%d'),'%d/%m/%Y') data_abordagens_socio_economicas,\n"
			+ "	subsidio_escolar,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_subsidio_escolar,'%Y-%m-%d'),'%d/%m/%Y') data_subsidio_escolar,\n"
			+ "	cuidados_pos_violencia_comunitarios,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_cuidados_pos_violencia_comunitarios,'%Y-%m-%d'),'%d/%m/%Y') data_cuidados_pos_violencia_comunitarios,\n"
			+ "	cuidados_pos_violencia_clinicos,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_cuidados_pos_violencia_clinicos,'%Y-%m-%d'),'%d/%m/%Y') data_cuidados_pos_violencia_clinicos,\n"
			+ "	outros_saaj,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_outros_saaj,'%Y-%m-%d'),'%d/%m/%Y') outros_saaj_date,\n"
			+ "	prep,\n"
			+ "	DATE_FORMAT(STR_TO_DATE(data_prep,'%Y-%m-%d'),'%d/%m/%Y') data_prep\n"
			+ "from(	\n"
			+ "	select distinct v.beneficiary_id,\n"
			+ "		pr.name provincia,\n"
			+ "		dt.name distrito,\n"
			+ "		v.nui,\n"
			+ "		v.current_age idade_actual,\n"
			+ "		if(v.current_age_band=1,'9-14', if(v.current_age_band=2,'15-19',if(v.current_age_band=3,'20-24',if(v.current_age_band=4,'25-29','')))) faixa_actual,\n"
			+ "		v.date_of_birth data_nascimento,\n"
			+ "		if (v.gender = 2 and v.current_age > 8\n"
			+ "			and((v.vblt_tested_hiv is not null and v.vblt_tested_hiv < 2 and v.date_created < :endDate)\n"
			+ "			or v.vblt_multiple_partners = 1 \n"
			+ "			or v.vblt_is_deficient = 1\n"
			+ "			or v.vblt_gbv_victim = 1\n"
			+ "			or v.vblt_alcohol_drugs_use = 1\n"
			+ "			or v.vblt_sti_history = 1\n"
			+ "			or v.vblt_sexual_exploitation = 1 \n"
			+ "			or ((v.vblt_house_sustainer = 1 or v.vblt_married_before=1 or v.vblt_pregnant_before = 1 or v.vblt_children = 1 or v.vblt_trafficking_victim=1 or v.vblt_is_migrant = 1) and v.current_age < 20)\n"
			+ "			or ((v.vblt_sexually_active = 1 or v.vblt_pregnant_or_breastfeeding = 1 or v.vblt_is_student = 0 or (v.vblt_is_employed is not null and v.vblt_is_employed <> 0) or v.vblt_is_orphan=1) and v.current_age < 18)\n"
			+ "			or (v.vblt_sex_worker = 1 and v.current_age > 17)),\n"
			+ "			1,0) agyw_prev,\n"
			+ "	    if(v.current_age < 20 and v.vblt_house_sustainer=1,1,0) +\n"
			+ "		if(v.current_age < 18 and v.vblt_is_orphan=1,1,0) +\n"
			+ "		if(v.current_age < 18 and v.vblt_is_student=0,1,0) +\n"
			+ "		if(v.vblt_is_deficient=1,1,0) +\n"
			+ "		if(v.current_age < 20 and v.vblt_married_before=1,1,0) +\n"
			+ "		if(v.current_age < 20 and v.vblt_pregnant_before=1,1,0) +\n"
			+ "		if(v.current_age < 20 and v.vblt_children=1,1,0) +\n"
			+ "		if(v.current_age < 18 and v.vblt_pregnant_or_breastfeeding=1,1,0) +\n"
			+ "		if(v.vblt_tested_hiv < 2 and v.date_created < :endDate,1,0) +\n"
			+ "		if(v.vblt_sexual_exploitation=1,1,0) +\n"
			+ "		if(v.current_age < 20 and vblt_is_migrant=1,1,0) +\n"
			+ "		if(v.current_age < 20 and v.vblt_trafficking_victim=1,1,0) +\n"
			+ "		if(v.current_age < 18 and v.vblt_sexually_active=1,1,0) +\n"
			+ "		if(v.vblt_multiple_partners=1,1,0) +\n"
			+ "		if(v.vblt_gbv_victim=1,1,0) +\n"
			+ "		if(v.current_age < 18 and v.vblt_is_employed<>0,1,0) +\n"
			+ "		if(v.current_age > 17 and v.vblt_sex_worker=1,1,0) +\n"
			+ "		if(v.vblt_alcohol_drugs_use=1,1,0) +\n"
			+ "		if(v.vblt_sti_history=1,1,0) as vulnerabilidades,\n"
			+ "		sum(case\n"
			+ "			when v.service_id in (20,44,45,46) then 1\n"
			+ "			else 0\n"
			+ "		end) recursos_sociais,\n"
			+ "		max(case\n"
			+ "			when v.service_id in (20,44,45,46) then max_data_servico\n"
			+ "		end) data_recursos_sociais,\n"
			+ "		sum(case\n"
			+ "			when v.service_id in (28,41,47,48,49) then 1\n"
			+ "			else 0\n"
			+ "		end) prevencao_hiv,\n"
			+ "		max(case\n"
			+ "			when v.service_id in (28,41,47,48,49) then max_data_servico\n"
			+ "		end) data_prevencao_hiv,\n"
			+ "		sum(case\n"
			+ "			when v.service_id in (43,50,51,52) then 1\n"
			+ "			else 0\n"
			+ "		end) prevencao_vgb,\n"
			+ "		max(case\n"
			+ "			when v.service_id in (43,50,51,52) then max_data_servico\n"
			+ "		end) data_prevencao_vgb,\n"
			+ "		sum(case\n"
			+ "			when v.service_id=37 then 1\n"
			+ "			else 0\n"
			+ "		end) educativas,\n"
			+ "		max(case\n"
			+ "			when v.service_id=37 then max_data_servico\n"
			+ "		end) data_educativas,\n"
			+ "		sum(case\n"
			+ "			when v.service_id in (55,56,57) then 1\n"
			+ "			else 0\n"
			+ "		end) literacia_financeira,\n"
			+ "		max(case\n"
			+ "			when v.service_id in (55,56,57) then max_data_servico\n"
			+ "		end) data_literacia_financeira,\n"
			+ "		sum(case\n"
			+ "			when v.service_id=9 then 1\n"
			+ "			else 0\n"
			+ "		end) ats,\n"
			+ "		max(case\n"
			+ "			when v.service_id=9 then max_data_servico\n"
			+ "		end) data_ats,\n"
			+ "		sum(case\n"
			+ "			when v.service_id=1 then 1\n"
			+ "			else 0\n"
			+ "		end) preservativos,\n"
			+ "		max(case\n"
			+ "			when v.service_id=1 then max_data_servico\n"
			+ "		end) data_preservativos,\n"
			+ "		sum(case\n"
			+ "			when v.service_id=2 then 1\n"
			+ "			else 0\n"
			+ "		end) contracepcao,\n"
			+ "		max(case\n"
			+ "			when v.service_id=2 then max_data_servico\n"
			+ "		end) data_contracepcao,\n"
			+ "		sum(case\n"
			+ "			when v.service_id=21 then 1\n"
			+ "			else 0\n"
			+ "		end) abordagens_socio_economicas,\n"
			+ "		max(case\n"
			+ "			when v.service_id=21 then max_data_servico\n"
			+ "		end) data_abordagens_socio_economicas,\n"
			+ "		sum(case\n"
			+ "			when v.service_id=18 then 1\n"
			+ "			else 0\n"
			+ "		end) subsidio_escolar,\n"
			+ "		max(case\n"
			+ "			when v.service_id=18 then max_data_servico\n"
			+ "		end) data_subsidio_escolar,\n"
			+ "		sum(case\n"
			+ "			when v.service_id=42 then 1\n"
			+ "			else 0\n"
			+ "		end) cuidados_pos_violencia_comunitarios,\n"
			+ "		max(case\n"
			+ "			when v.service_id=42 then max_data_servico\n"
			+ "		end) data_cuidados_pos_violencia_comunitarios,\n"
			+ "		sum(case\n"
			+ "			when v.service_id=3 then 1\n"
			+ "			else 0\n"
			+ "		end) cuidados_pos_violencia_clinicos,\n"
			+ "		max(case\n"
			+ "			when v.service_id=3 then max_data_servico\n"
			+ "		end) data_cuidados_pos_violencia_clinicos,\n"
			+ "		sum(case\n"
			+ "			when v.service_id=36 then 1\n"
			+ "			else 0\n"
			+ "		end) outros_saaj,\n"
			+ "		max(case\n"
			+ "			when v.service_id=36 then max_data_servico\n"
			+ "		end) data_outros_saaj,\n"
			+ "		sum(case\n"
			+ "			when v.service_id=54 then 1\n"
			+ "			else 0\n"
			+ "		end) prep,\n"
			+ "		max(case\n"
			+ "			when v.service_id=54 then max_data_servico\n"
			+ "		end) data_prep\n"
			+ "	from\n"
			+ "	(\n"
			+ "		select beneficiary_id,max(service_date)\n"
			+ "		from agyw_prev_mview\n"
			+ "		where service_date between :startDate and :endDate		\n"
			+ "		and intervention_status = 1\n"
			+ "		group by beneficiary_id\n"
			+ "	) servico_ano\n"
			+ "	inner join \n"
			+ "	(	select *,max(service_date) max_data_servico\n"
			+ "		from agyw_prev_mview\n"
			+ "		where intervention_status=1\n"
			+ "		-- and provincia_id=2\n"
			+ "		group by beneficiary_id,service_id,sub_service_id\n"
			+ "	) v on servico_ano.beneficiary_id=v.beneficiary_id\n"
			+ "	left join province pr on v.province_id = pr.id\n"
			+ "	left join district dt on v.district_id = dt.id\n"
			+ "	left join neighborhood n on v.neighborhood_id = n.id\n"
			+ "	left join partners pa on v.organization_id = pa.id\n"
			+ "	where v.service_date <= :endDate\n"
			+ "	-- and v.vulneravel=1\n"
			+ "	-- and pr.id=2 -- Provícias (1-Maputo Cidade, 2-Maputo Província, 3-Gaza, 4-Inhambane, 5-Sofala, 6-Manica, 7-Tete, 8-Zambézia, 9-Nampula, 10-Cabo-Delgado, 11-Niassa)\n"
			+ "	and dt.id = :district\n"
			+ "	group by v.beneficiary_id\n"
			+ ") a\n"
			+ "left join dreams_db.references r on r.beneficiary_id=a.beneficiary_id and r.status=0\n"
			+ "LEFT JOIN users u ON r.user_created = u.id -- tabela de usuarios registados6\n"
			+ "LEFT JOIN partners pa ON u.partner_id = pa.id -- tabela de parceiros Dreams\n"
			+ "-- LEFT JOIN app_dream_parceiros_tipo pt ON pt.id=dp.parceria_id -- tabela por tipo de parceiro (CM/US/ES)\n"
			+ "group by a.beneficiary_id\n"
			+ "order by provincia,distrito,nui";
}
