package domains;
// Generated Jun 13, 2022, 9:28:17 AM by Hibernate Tools 5.4.12.Final

import java.util.Date;

/**
 * BeneficiariesInterventions generated by hbm2java
 */
public class BeneficiariesInterventions implements java.io.Serializable {

	private BeneficiariesInterventionsId id;
	private Beneficiaries beneficiaries;
	private SubServices subServices;
	private Us us;
	private String result;
	private Integer activistId;
	private String entryPoint;
	private String provider;
	private String remarks;
	private int status;
	private int createdBy;
	private Date dateCreated;
	private String updatedBy;
	private Date dateUpdated;
	private String offlineId;

	public BeneficiariesInterventions() {
	}

	public BeneficiariesInterventions(BeneficiariesInterventionsId id, Beneficiaries beneficiaries,
			SubServices subServices, Us us, String entryPoint, int status, int createdBy, Date dateCreated) {
		this.id = id;
		this.beneficiaries = beneficiaries;
		this.subServices = subServices;
		this.us = us;
		this.entryPoint = entryPoint;
		this.status = status;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	public BeneficiariesInterventions(BeneficiariesInterventionsId id, Beneficiaries beneficiaries,
			SubServices subServices, Us us, String result, Integer activistId, String entryPoint, String provider,
			String remarks, int status, int createdBy, Date dateCreated, String updatedBy, Date dateUpdated,
			String offlineId) {
		this.id = id;
		this.beneficiaries = beneficiaries;
		this.subServices = subServices;
		this.us = us;
		this.result = result;
		this.activistId = activistId;
		this.entryPoint = entryPoint;
		this.provider = provider;
		this.remarks = remarks;
		this.status = status;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.updatedBy = updatedBy;
		this.dateUpdated = dateUpdated;
		this.offlineId = offlineId;
	}

	public BeneficiariesInterventionsId getId() {
		return this.id;
	}

	public void setId(BeneficiariesInterventionsId id) {
		this.id = id;
	}

	public Beneficiaries getBeneficiaries() {
		return this.beneficiaries;
	}

	public void setBeneficiaries(Beneficiaries beneficiaries) {
		this.beneficiaries = beneficiaries;
	}

	public SubServices getSubServices() {
		return this.subServices;
	}

	public void setSubServices(SubServices subServices) {
		this.subServices = subServices;
	}

	public Us getUs() {
		return this.us;
	}

	public void setUs(Us us) {
		this.us = us;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public Integer getActivistId() {
		return this.activistId;
	}

	public void setActivistId(Integer activistId) {
		this.activistId = activistId;
	}

	public String getEntryPoint() {
		return this.entryPoint;
	}

	public void setEntryPoint(String entryPoint) {
		this.entryPoint = entryPoint;
	}

	public String getProvider() {
		return this.provider;
	}

	public void setProvider(String provider) {
		this.provider = provider;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	public String getOfflineId() {
		return this.offlineId;
	}

	public void setOfflineId(String offlineId) {
		this.offlineId = offlineId;
	}

}
