package domains;
// Generated Jun 13, 2022, 9:28:17 AM by Hibernate Tools 5.4.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Beneficiaries generated by hbm2java
 */
public class Beneficiaries implements java.io.Serializable {

	private Integer id;
	private Neighborhood neighborhood;
	private Partners partners;
	private Us us;
	private String nui;
	private String surname;
	private String name;
	private String nickName;
	private Integer organizationId;
	private Date dateOfBirth;
	private char gender;
	private String address;
	private String phoneNumber;
	private String EMail;
	private Integer via;
	private Integer partnerId;
	private String entryPoint;
	private String vbltLivesWith;
	private Byte vbltIsOrphan;
	private Byte vbltIsStudent;
	private Integer vbltSchoolGrade;
	private String vbltSchoolName;
	private Byte vbltIsDeficient;
	private String vbltDeficiencyType;
	private Byte vbltMarriedBefore;
	private Byte vbltPregnantBefore;
	private Byte vbltChildren;
	private Byte vbltPregnantOrBreastfeeding;
	private String vbltIsEmployed;
	private String vbltTestedHiv;
	private Byte vbltSexuallyActive;
	private Byte vbltMultiplePartners;
	private Byte vbltIsMigrant;
	private Byte vbltTraffickingVictim;
	private Byte vbltSexualExploitation;
	private String vbltSexploitationTime;
	private Byte vbltVbgVictim;
	private String vbltVbgType;
	private String vbltVbgTime;
	private Byte vbltAlcoholDrugsUse;
	private Byte vbltStiHistory;
	private Byte vbltSexWorker;
	private Byte vbltHouseSustainer;
	private int status;
	private int createdBy;
	private Date dateCreated;
	private Integer updatedBy;
	private Date dateUpdated;
	private String offlineId;
	private Set vulnerabilityHistories = new HashSet(0);
	private Set beneficiariesInterventionses = new HashSet(0);
	private Set referenceses = new HashSet(0);

	public Beneficiaries() {
	}

	public Beneficiaries(Neighborhood neighborhood, Us us, String nui, String surname, String name, String nickName,
			Date dateOfBirth, char gender, String entryPoint, int status, int createdBy, Date dateCreated) {
		this.neighborhood = neighborhood;
		this.us = us;
		this.nui = nui;
		this.surname = surname;
		this.name = name;
		this.nickName = nickName;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.entryPoint = entryPoint;
		this.status = status;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	public Beneficiaries(Neighborhood neighborhood, Partners partners, Us us, String nui, String surname, String name,
			String nickName, Integer organizationId, Date dateOfBirth, char gender, String address, String phoneNumber,
			String EMail, Integer via, Integer partnerId, String entryPoint, String vbltLivesWith, Byte vbltIsOrphan,
			Byte vbltIsStudent, Integer vbltSchoolGrade, String vbltSchoolName, Byte vbltIsDeficient,
			String vbltDeficiencyType, Byte vbltMarriedBefore, Byte vbltPregnantBefore, Byte vbltChildren,
			Byte vbltPregnantOrBreastfeeding, String vbltIsEmployed, String vbltTestedHiv, Byte vbltSexuallyActive,
			Byte vbltMultiplePartners, Byte vbltIsMigrant, Byte vbltTraffickingVictim, Byte vbltSexualExploitation,
			String vbltSexploitationTime, Byte vbltVbgVictim, String vbltVbgType, String vbltVbgTime,
			Byte vbltAlcoholDrugsUse, Byte vbltStiHistory, Byte vbltSexWorker, Byte vbltHouseSustainer, int status,
			int createdBy, Date dateCreated, Integer updatedBy, Date dateUpdated, String offlineId,
			Set vulnerabilityHistories, Set beneficiariesInterventionses, Set referenceses) {
		this.neighborhood = neighborhood;
		this.partners = partners;
		this.us = us;
		this.nui = nui;
		this.surname = surname;
		this.name = name;
		this.nickName = nickName;
		this.organizationId = organizationId;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.EMail = EMail;
		this.via = via;
		this.partnerId = partnerId;
		this.entryPoint = entryPoint;
		this.vbltLivesWith = vbltLivesWith;
		this.vbltIsOrphan = vbltIsOrphan;
		this.vbltIsStudent = vbltIsStudent;
		this.vbltSchoolGrade = vbltSchoolGrade;
		this.vbltSchoolName = vbltSchoolName;
		this.vbltIsDeficient = vbltIsDeficient;
		this.vbltDeficiencyType = vbltDeficiencyType;
		this.vbltMarriedBefore = vbltMarriedBefore;
		this.vbltPregnantBefore = vbltPregnantBefore;
		this.vbltChildren = vbltChildren;
		this.vbltPregnantOrBreastfeeding = vbltPregnantOrBreastfeeding;
		this.vbltIsEmployed = vbltIsEmployed;
		this.vbltTestedHiv = vbltTestedHiv;
		this.vbltSexuallyActive = vbltSexuallyActive;
		this.vbltMultiplePartners = vbltMultiplePartners;
		this.vbltIsMigrant = vbltIsMigrant;
		this.vbltTraffickingVictim = vbltTraffickingVictim;
		this.vbltSexualExploitation = vbltSexualExploitation;
		this.vbltSexploitationTime = vbltSexploitationTime;
		this.vbltVbgVictim = vbltVbgVictim;
		this.vbltVbgType = vbltVbgType;
		this.vbltVbgTime = vbltVbgTime;
		this.vbltAlcoholDrugsUse = vbltAlcoholDrugsUse;
		this.vbltStiHistory = vbltStiHistory;
		this.vbltSexWorker = vbltSexWorker;
		this.vbltHouseSustainer = vbltHouseSustainer;
		this.status = status;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.updatedBy = updatedBy;
		this.dateUpdated = dateUpdated;
		this.offlineId = offlineId;
		this.vulnerabilityHistories = vulnerabilityHistories;
		this.beneficiariesInterventionses = beneficiariesInterventionses;
		this.referenceses = referenceses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Neighborhood getNeighborhood() {
		return this.neighborhood;
	}

	public void setNeighborhood(Neighborhood neighborhood) {
		this.neighborhood = neighborhood;
	}

	public Partners getPartners() {
		return this.partners;
	}

	public void setPartners(Partners partners) {
		this.partners = partners;
	}

	public Us getUs() {
		return this.us;
	}

	public void setUs(Us us) {
		this.us = us;
	}

	public String getNui() {
		return this.nui;
	}

	public void setNui(String nui) {
		this.nui = nui;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public Integer getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(Integer organizationId) {
		this.organizationId = organizationId;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public char getGender() {
		return this.gender;
	}

	public void setGender(char gender) {
		this.gender = gender;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	public Integer getVia() {
		return this.via;
	}

	public void setVia(Integer via) {
		this.via = via;
	}

	public Integer getPartnerId() {
		return this.partnerId;
	}

	public void setPartnerId(Integer partnerId) {
		this.partnerId = partnerId;
	}

	public String getEntryPoint() {
		return this.entryPoint;
	}

	public void setEntryPoint(String entryPoint) {
		this.entryPoint = entryPoint;
	}

	public String getVbltLivesWith() {
		return this.vbltLivesWith;
	}

	public void setVbltLivesWith(String vbltLivesWith) {
		this.vbltLivesWith = vbltLivesWith;
	}

	public Byte getVbltIsOrphan() {
		return this.vbltIsOrphan;
	}

	public void setVbltIsOrphan(Byte vbltIsOrphan) {
		this.vbltIsOrphan = vbltIsOrphan;
	}

	public Byte getVbltIsStudent() {
		return this.vbltIsStudent;
	}

	public void setVbltIsStudent(Byte vbltIsStudent) {
		this.vbltIsStudent = vbltIsStudent;
	}

	public Integer getVbltSchoolGrade() {
		return this.vbltSchoolGrade;
	}

	public void setVbltSchoolGrade(Integer vbltSchoolGrade) {
		this.vbltSchoolGrade = vbltSchoolGrade;
	}

	public String getVbltSchoolName() {
		return this.vbltSchoolName;
	}

	public void setVbltSchoolName(String vbltSchoolName) {
		this.vbltSchoolName = vbltSchoolName;
	}

	public Byte getVbltIsDeficient() {
		return this.vbltIsDeficient;
	}

	public void setVbltIsDeficient(Byte vbltIsDeficient) {
		this.vbltIsDeficient = vbltIsDeficient;
	}

	public String getVbltDeficiencyType() {
		return this.vbltDeficiencyType;
	}

	public void setVbltDeficiencyType(String vbltDeficiencyType) {
		this.vbltDeficiencyType = vbltDeficiencyType;
	}

	public Byte getVbltMarriedBefore() {
		return this.vbltMarriedBefore;
	}

	public void setVbltMarriedBefore(Byte vbltMarriedBefore) {
		this.vbltMarriedBefore = vbltMarriedBefore;
	}

	public Byte getVbltPregnantBefore() {
		return this.vbltPregnantBefore;
	}

	public void setVbltPregnantBefore(Byte vbltPregnantBefore) {
		this.vbltPregnantBefore = vbltPregnantBefore;
	}

	public Byte getVbltChildren() {
		return this.vbltChildren;
	}

	public void setVbltChildren(Byte vbltChildren) {
		this.vbltChildren = vbltChildren;
	}

	public Byte getVbltPregnantOrBreastfeeding() {
		return this.vbltPregnantOrBreastfeeding;
	}

	public void setVbltPregnantOrBreastfeeding(Byte vbltPregnantOrBreastfeeding) {
		this.vbltPregnantOrBreastfeeding = vbltPregnantOrBreastfeeding;
	}

	public String getVbltIsEmployed() {
		return this.vbltIsEmployed;
	}

	public void setVbltIsEmployed(String vbltIsEmployed) {
		this.vbltIsEmployed = vbltIsEmployed;
	}

	public String getVbltTestedHiv() {
		return this.vbltTestedHiv;
	}

	public void setVbltTestedHiv(String vbltTestedHiv) {
		this.vbltTestedHiv = vbltTestedHiv;
	}

	public Byte getVbltSexuallyActive() {
		return this.vbltSexuallyActive;
	}

	public void setVbltSexuallyActive(Byte vbltSexuallyActive) {
		this.vbltSexuallyActive = vbltSexuallyActive;
	}

	public Byte getVbltMultiplePartners() {
		return this.vbltMultiplePartners;
	}

	public void setVbltMultiplePartners(Byte vbltMultiplePartners) {
		this.vbltMultiplePartners = vbltMultiplePartners;
	}

	public Byte getVbltIsMigrant() {
		return this.vbltIsMigrant;
	}

	public void setVbltIsMigrant(Byte vbltIsMigrant) {
		this.vbltIsMigrant = vbltIsMigrant;
	}

	public Byte getVbltTraffickingVictim() {
		return this.vbltTraffickingVictim;
	}

	public void setVbltTraffickingVictim(Byte vbltTraffickingVictim) {
		this.vbltTraffickingVictim = vbltTraffickingVictim;
	}

	public Byte getVbltSexualExploitation() {
		return this.vbltSexualExploitation;
	}

	public void setVbltSexualExploitation(Byte vbltSexualExploitation) {
		this.vbltSexualExploitation = vbltSexualExploitation;
	}

	public String getVbltSexploitationTime() {
		return this.vbltSexploitationTime;
	}

	public void setVbltSexploitationTime(String vbltSexploitationTime) {
		this.vbltSexploitationTime = vbltSexploitationTime;
	}

	public Byte getVbltVbgVictim() {
		return this.vbltVbgVictim;
	}

	public void setVbltVbgVictim(Byte vbltVbgVictim) {
		this.vbltVbgVictim = vbltVbgVictim;
	}

	public String getVbltVbgType() {
		return this.vbltVbgType;
	}

	public void setVbltVbgType(String vbltVbgType) {
		this.vbltVbgType = vbltVbgType;
	}

	public String getVbltVbgTime() {
		return this.vbltVbgTime;
	}

	public void setVbltVbgTime(String vbltVbgTime) {
		this.vbltVbgTime = vbltVbgTime;
	}

	public Byte getVbltAlcoholDrugsUse() {
		return this.vbltAlcoholDrugsUse;
	}

	public void setVbltAlcoholDrugsUse(Byte vbltAlcoholDrugsUse) {
		this.vbltAlcoholDrugsUse = vbltAlcoholDrugsUse;
	}

	public Byte getVbltStiHistory() {
		return this.vbltStiHistory;
	}

	public void setVbltStiHistory(Byte vbltStiHistory) {
		this.vbltStiHistory = vbltStiHistory;
	}

	public Byte getVbltSexWorker() {
		return this.vbltSexWorker;
	}

	public void setVbltSexWorker(Byte vbltSexWorker) {
		this.vbltSexWorker = vbltSexWorker;
	}

	public Byte getVbltHouseSustainer() {
		return this.vbltHouseSustainer;
	}

	public void setVbltHouseSustainer(Byte vbltHouseSustainer) {
		this.vbltHouseSustainer = vbltHouseSustainer;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	public String getOfflineId() {
		return this.offlineId;
	}

	public void setOfflineId(String offlineId) {
		this.offlineId = offlineId;
	}

	public Set getVulnerabilityHistories() {
		return this.vulnerabilityHistories;
	}

	public void setVulnerabilityHistories(Set vulnerabilityHistories) {
		this.vulnerabilityHistories = vulnerabilityHistories;
	}

	public Set getBeneficiariesInterventionses() {
		return this.beneficiariesInterventionses;
	}

	public void setBeneficiariesInterventionses(Set beneficiariesInterventionses) {
		this.beneficiariesInterventionses = beneficiariesInterventionses;
	}

	public Set getReferenceses() {
		return this.referenceses;
	}

	public void setReferenceses(Set referenceses) {
		this.referenceses = referenceses;
	}

}
