package domains;
// Generated Jun 13, 2022, 9:28:17 AM by Hibernate Tools 5.4.12.Final

import java.util.Date;

/**
 * BeneficiariesInterventionsId generated by hbm2java
 */
public class BeneficiariesInterventionsId implements java.io.Serializable {

	private int beneficiaryId;
	private int subServiceId;
	private Date date;

	public BeneficiariesInterventionsId() {
	}

	public BeneficiariesInterventionsId(int beneficiaryId, int subServiceId, Date date) {
		this.beneficiaryId = beneficiaryId;
		this.subServiceId = subServiceId;
		this.date = date;
	}

	public int getBeneficiaryId() {
		return this.beneficiaryId;
	}

	public void setBeneficiaryId(int beneficiaryId) {
		this.beneficiaryId = beneficiaryId;
	}

	public int getSubServiceId() {
		return this.subServiceId;
	}

	public void setSubServiceId(int subServiceId) {
		this.subServiceId = subServiceId;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BeneficiariesInterventionsId))
			return false;
		BeneficiariesInterventionsId castOther = (BeneficiariesInterventionsId) other;

		return (this.getBeneficiaryId() == castOther.getBeneficiaryId())
				&& (this.getSubServiceId() == castOther.getSubServiceId())
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBeneficiaryId();
		result = 37 * result + this.getSubServiceId();
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

}
