package domains;
// Generated Jun 13, 2022, 9:28:17 AM by Hibernate Tools 5.4.12.Final

import java.util.Date;

/**
 * CurriculumsServices generated by hbm2java
 */
public class CurriculumsServices implements java.io.Serializable {

	private CurriculumsServicesId id;
	private Curriculums curriculums;
	private Services services;
	private String description;
	private int status;
	private int createdBy;
	private Date dateCreated;
	private Integer updatedBy;
	private Date dateUpdated;

	public CurriculumsServices() {
	}

	public CurriculumsServices(CurriculumsServicesId id, Curriculums curriculums, Services services, int status,
			int createdBy, Date dateCreated) {
		this.id = id;
		this.curriculums = curriculums;
		this.services = services;
		this.status = status;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	public CurriculumsServices(CurriculumsServicesId id, Curriculums curriculums, Services services, String description,
			int status, int createdBy, Date dateCreated, Integer updatedBy, Date dateUpdated) {
		this.id = id;
		this.curriculums = curriculums;
		this.services = services;
		this.description = description;
		this.status = status;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.updatedBy = updatedBy;
		this.dateUpdated = dateUpdated;
	}

	public CurriculumsServicesId getId() {
		return this.id;
	}

	public void setId(CurriculumsServicesId id) {
		this.id = id;
	}

	public Curriculums getCurriculums() {
		return this.curriculums;
	}

	public void setCurriculums(Curriculums curriculums) {
		this.curriculums = curriculums;
	}

	public Services getServices() {
		return this.services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

}
