package domains;
// Generated Jun 13, 2022, 9:28:17 AM by Hibernate Tools 5.4.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * District generated by hbm2java
 */
public class District implements java.io.Serializable {

	private Integer id;
	private Province province;
	private String code;
	private String name;
	private int status;
	private int createdBy;
	private Date dateCreated;
	private Integer updatedBy;
	private Date dateUpdated;
	private Set partnerses = new HashSet(0);
	private Set localities = new HashSet(0);

	public District() {
	}

	public District(Province province, String code, String name, int status, int createdBy, Date dateCreated) {
		this.province = province;
		this.code = code;
		this.name = name;
		this.status = status;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	public District(Province province, String code, String name, int status, int createdBy, Date dateCreated,
			Integer updatedBy, Date dateUpdated, Set partnerses, Set localities) {
		this.province = province;
		this.code = code;
		this.name = name;
		this.status = status;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.updatedBy = updatedBy;
		this.dateUpdated = dateUpdated;
		this.partnerses = partnerses;
		this.localities = localities;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Province getProvince() {
		return this.province;
	}

	public void setProvince(Province province) {
		this.province = province;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	public Set getPartnerses() {
		return this.partnerses;
	}

	public void setPartnerses(Set partnerses) {
		this.partnerses = partnerses;
	}

	public Set getLocalities() {
		return this.localities;
	}

	public void setLocalities(Set localities) {
		this.localities = localities;
	}

}
