package domains;
// Generated Jun 13, 2022, 9:28:17 AM by Hibernate Tools 5.4.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partners generated by hbm2java
 */
public class Partners implements java.io.Serializable {

	private Integer id;
	private District district;
	private String name;
	private String abbreviation;
	private String description;
	private String partnerType;
	private String logo;
	private int status;
	private int createdBy;
	private Date dateCreated;
	private Integer updatedBy;
	private Date dateUpdated;
	private Set userses = new HashSet(0);
	private Set beneficiarieses = new HashSet(0);

	public Partners() {
	}

	public Partners(String name, String partnerType, int status, int createdBy, Date dateCreated) {
		this.name = name;
		this.partnerType = partnerType;
		this.status = status;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	public Partners(District district, String name, String abbreviation, String description, String partnerType,
			String logo, int status, int createdBy, Date dateCreated, Integer updatedBy, Date dateUpdated, Set userses,
			Set beneficiarieses) {
		this.district = district;
		this.name = name;
		this.abbreviation = abbreviation;
		this.description = description;
		this.partnerType = partnerType;
		this.logo = logo;
		this.status = status;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.updatedBy = updatedBy;
		this.dateUpdated = dateUpdated;
		this.userses = userses;
		this.beneficiarieses = beneficiarieses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAbbreviation() {
		return this.abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getPartnerType() {
		return this.partnerType;
	}

	public void setPartnerType(String partnerType) {
		this.partnerType = partnerType;
	}

	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

	public Set getBeneficiarieses() {
		return this.beneficiarieses;
	}

	public void setBeneficiarieses(Set beneficiarieses) {
		this.beneficiarieses = beneficiarieses;
	}

}
