package domains;
// Generated Jun 13, 2022, 9:28:17 AM by Hibernate Tools 5.4.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Profiles generated by hbm2java
 */
public class Profiles implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Date dateCreated;
	private Integer createdBy;
	private Date dateUpdated;
	private Integer updatedBy;
	private Set userses = new HashSet(0);

	public Profiles() {
	}

	public Profiles(String name) {
		this.name = name;
	}

	public Profiles(String name, String description, Date dateCreated, Integer createdBy, Date dateUpdated,
			Integer updatedBy, Set userses) {
		this.name = name;
		this.description = description;
		this.dateCreated = dateCreated;
		this.createdBy = createdBy;
		this.dateUpdated = dateUpdated;
		this.updatedBy = updatedBy;
		this.userses = userses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
