package domains;
// Generated Jun 13, 2022, 9:28:17 AM by Hibernate Tools 5.4.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Province generated by hbm2java
 */
public class Province implements java.io.Serializable {

	private Integer id;
	private String code;
	private String name;
	private int status;
	private int createdBy;
	private Date createDate;
	private Integer updatedBy;
	private Date updateDate;
	private Set districts = new HashSet(0);

	public Province() {
	}

	public Province(String code, String name, int status, int createdBy, Date createDate) {
		this.code = code;
		this.name = name;
		this.status = status;
		this.createdBy = createdBy;
		this.createDate = createDate;
	}

	public Province(String code, String name, int status, int createdBy, Date createDate, Integer updatedBy,
			Date updateDate, Set districts) {
		this.code = code;
		this.name = name;
		this.status = status;
		this.createdBy = createdBy;
		this.createDate = createDate;
		this.updatedBy = updatedBy;
		this.updateDate = updateDate;
		this.districts = districts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Set getDistricts() {
		return this.districts;
	}

	public void setDistricts(Set districts) {
		this.districts = districts;
	}

}
