package domains;
// Generated Jun 13, 2022, 9:28:17 AM by Hibernate Tools 5.4.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * References generated by hbm2java
 */
public class References implements java.io.Serializable {

	private Integer id;
	private Beneficiaries beneficiaries;
	private Users users;
	private String referenceNote;
	private String description;
	private String referTo;
	private String bookNumber;
	private String referenceCode;
	private String serviceType;
	private String remarks;
	private int statusRef;
	private Integer status;
	private Integer cancelReason;
	private String otherReason;
	private int createdBy;
	private Date dateCreated;
	private Integer updatedBy;
	private Date dateUpdated;
	private Set referencesServiceses = new HashSet(0);

	public References() {
	}

	public References(Beneficiaries beneficiaries, Users users, String referTo, int statusRef, int createdBy,
			Date dateCreated) {
		this.beneficiaries = beneficiaries;
		this.users = users;
		this.referTo = referTo;
		this.statusRef = statusRef;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	public References(Beneficiaries beneficiaries, Users users, String referenceNote, String description,
			String referTo, String bookNumber, String referenceCode, String serviceType, String remarks, int statusRef,
			Integer status, Integer cancelReason, String otherReason, int createdBy, Date dateCreated,
			Integer updatedBy, Date dateUpdated, Set referencesServiceses) {
		this.beneficiaries = beneficiaries;
		this.users = users;
		this.referenceNote = referenceNote;
		this.description = description;
		this.referTo = referTo;
		this.bookNumber = bookNumber;
		this.referenceCode = referenceCode;
		this.serviceType = serviceType;
		this.remarks = remarks;
		this.statusRef = statusRef;
		this.status = status;
		this.cancelReason = cancelReason;
		this.otherReason = otherReason;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.updatedBy = updatedBy;
		this.dateUpdated = dateUpdated;
		this.referencesServiceses = referencesServiceses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Beneficiaries getBeneficiaries() {
		return this.beneficiaries;
	}

	public void setBeneficiaries(Beneficiaries beneficiaries) {
		this.beneficiaries = beneficiaries;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getReferenceNote() {
		return this.referenceNote;
	}

	public void setReferenceNote(String referenceNote) {
		this.referenceNote = referenceNote;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getReferTo() {
		return this.referTo;
	}

	public void setReferTo(String referTo) {
		this.referTo = referTo;
	}

	public String getBookNumber() {
		return this.bookNumber;
	}

	public void setBookNumber(String bookNumber) {
		this.bookNumber = bookNumber;
	}

	public String getReferenceCode() {
		return this.referenceCode;
	}

	public void setReferenceCode(String referenceCode) {
		this.referenceCode = referenceCode;
	}

	public String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public int getStatusRef() {
		return this.statusRef;
	}

	public void setStatusRef(int statusRef) {
		this.statusRef = statusRef;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getCancelReason() {
		return this.cancelReason;
	}

	public void setCancelReason(Integer cancelReason) {
		this.cancelReason = cancelReason;
	}

	public String getOtherReason() {
		return this.otherReason;
	}

	public void setOtherReason(String otherReason) {
		this.otherReason = otherReason;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	public Set getReferencesServiceses() {
		return this.referencesServiceses;
	}

	public void setReferencesServiceses(Set referencesServiceses) {
		this.referencesServiceses = referencesServiceses;
	}

}
