package domains;
// Generated Jun 13, 2022, 9:28:17 AM by Hibernate Tools 5.4.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Services generated by hbm2java
 */
public class Services implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Integer coreService;
	private Integer hidden;
	private String serviceType;
	private String ageBands;
	private Integer status;
	private int createdBy;
	private Date dateCreated;
	private Integer updatedBy;
	private Date dateUpdated;
	private Set referencesServiceses = new HashSet(0);
	private Set subServiceses = new HashSet(0);
	private Set curriculumsServiceses = new HashSet(0);

	public Services() {
	}

	public Services(String name, String serviceType, int createdBy, Date dateCreated) {
		this.name = name;
		this.serviceType = serviceType;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	public Services(String name, String description, Integer coreService, Integer hidden, String serviceType,
			String ageBands, Integer status, int createdBy, Date dateCreated, Integer updatedBy, Date dateUpdated,
			Set referencesServiceses, Set subServiceses, Set curriculumsServiceses) {
		this.name = name;
		this.description = description;
		this.coreService = coreService;
		this.hidden = hidden;
		this.serviceType = serviceType;
		this.ageBands = ageBands;
		this.status = status;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.updatedBy = updatedBy;
		this.dateUpdated = dateUpdated;
		this.referencesServiceses = referencesServiceses;
		this.subServiceses = subServiceses;
		this.curriculumsServiceses = curriculumsServiceses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getCoreService() {
		return this.coreService;
	}

	public void setCoreService(Integer coreService) {
		this.coreService = coreService;
	}

	public Integer getHidden() {
		return this.hidden;
	}

	public void setHidden(Integer hidden) {
		this.hidden = hidden;
	}

	public String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

	public String getAgeBands() {
		return this.ageBands;
	}

	public void setAgeBands(String ageBands) {
		this.ageBands = ageBands;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	public Set getReferencesServiceses() {
		return this.referencesServiceses;
	}

	public void setReferencesServiceses(Set referencesServiceses) {
		this.referencesServiceses = referencesServiceses;
	}

	public Set getSubServiceses() {
		return this.subServiceses;
	}

	public void setSubServiceses(Set subServiceses) {
		this.subServiceses = subServiceses;
	}

	public Set getCurriculumsServiceses() {
		return this.curriculumsServiceses;
	}

	public void setCurriculumsServiceses(Set curriculumsServiceses) {
		this.curriculumsServiceses = curriculumsServiceses;
	}

}
