package dlt.dltbackendmaster.domain;
// Generated Jun 13, 2022, 9:37:47 AM by Hibernate Tools 5.2.12.Final

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.NamedQueries;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.node.ObjectNode;

import dlt.dltbackendmaster.domain.watermelondb.BeneficiaryInterventionSyncModel;
import dlt.dltbackendmaster.serializers.BeneficiarySerializer;
import dlt.dltbackendmaster.serializers.LocalitySerializer;
import dlt.dltbackendmaster.serializers.UsSerializer;

/**
 * BeneficiariesInterventions generated by hbm2java
 */
@Entity
@Table(name = "beneficiaries_interventions", catalog = "dreams_db")
@NamedQueries({ 
	@NamedQuery(name = "BeneficiariesInterventions.findAll", query = "SELECT b FROM BeneficiariesInterventions b"),
	@NamedQuery(name = "BeneficiariesInterventions.findByBeneficiaryAndSubService", 
		query = "SELECT b FROM BeneficiariesInterventions b where b.beneficiaries.id = :beneficiary_id and b.subServices.id = :sub_service_id"),
	@NamedQuery(name = "BeneficiariesInterventions.findByDateCreated", 
		query = "select b from BeneficiariesInterventions b where b.dateUpdated is null and b.dateCreated > :lastpulledat"),
	@NamedQuery(name = "BeneficiariesInterventions.findByDateUpdated",
		query = "select b from BeneficiariesInterventions b where (b.dateUpdated >= :lastpulledat) or (b.dateUpdated >= :lastpulledat and b.dateCreated = b.dateUpdated)") })
public class BeneficiariesInterventions implements java.io.Serializable {

	private BeneficiariesInterventionsId id;
	private Beneficiaries beneficiaries;
	private SubServices subServices;
	private Us us;
	private String result;
	private Integer activistId;
	private String entryPoint;
	private String provider;
	private String remarks;
	private int status;
	private int createdBy;
	private Date dateCreated;
	private String updatedBy;
	private Date dateUpdated;
	private String offlineId;

	public BeneficiariesInterventions() {
	}

	public BeneficiariesInterventions(BeneficiariesInterventionsId id, Beneficiaries beneficiaries,
			SubServices subServices, Us us, String entryPoint, int status, int createdBy, Date dateCreated) {
		this.id = id;
		this.beneficiaries = beneficiaries;
		this.subServices = subServices;
		this.us = us;
		this.entryPoint = entryPoint;
		this.status = status;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	public BeneficiariesInterventions(BeneficiariesInterventionsId id, Beneficiaries beneficiaries,
			SubServices subServices, Us us, String result, Integer activistId, String entryPoint, String provider,
			String remarks, int status, int createdBy, Date dateCreated, String updatedBy, Date dateUpdated,
			String offlineId) {
		this.id = id;
		this.beneficiaries = beneficiaries;
		this.subServices = subServices;
		this.us = us;
		this.result = result;
		this.activistId = activistId;
		this.entryPoint = entryPoint;
		this.provider = provider;
		this.remarks = remarks;
		this.status = status;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.updatedBy = updatedBy;
		this.dateUpdated = dateUpdated;
		this.offlineId = offlineId;
	}
	
	public BeneficiariesInterventions(BeneficiaryInterventionSyncModel model, String timestamp) throws ParseException {
        Long t = Long.valueOf(timestamp);
        Date regDate = new Date(t);
        this.beneficiaries = new Beneficiaries(model.getBeneficiary_id());
        this.subServices = new SubServices(model.getSub_service_id());
        this.result = model.getResult();
        DateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");
        Date date1=dateFormatter.parse(model.getDate());  
        this.id.setDate(date1);
        this.us = new Us(model.getUs_id());
        this.activistId = model.getActivist_id();
        this.entryPoint = model.getEntry_point();
        this.provider = model.getProvider();
        this.remarks = model.getRemarks();
        this.status = model.getStatus();
        //this.offlineId = model.getBeneficiary_id() + "" + model.getSub_service_id();
        this.offlineId = model.getId();
        this.dateCreated = regDate;
        this.dateUpdated = regDate;
    }

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "beneficiaryId", column = @Column(name = "beneficiary_id", nullable = false)),
			@AttributeOverride(name = "subServiceId", column = @Column(name = "sub_service_id", nullable = false)),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false, length = 10)) })
	public BeneficiariesInterventionsId getId() {
		return this.id;
	}

	public void setId(BeneficiariesInterventionsId id) {
		this.id = id;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "beneficiary_id", nullable = false, insertable = false, updatable = false)
	@JsonProperty("beneficiary")
    @JsonSerialize(using = BeneficiarySerializer.class)
	public Beneficiaries getBeneficiaries() {
		return this.beneficiaries;
	}

	public void setBeneficiaries(Beneficiaries beneficiaries) {
		this.beneficiaries = beneficiaries;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "sub_service_id", nullable = false, insertable = false, updatable = false)
	public SubServices getSubServices() {
		return this.subServices;
	}

	public void setSubServices(SubServices subServices) {
		this.subServices = subServices;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "us_id", nullable = false)
	@JsonProperty("us")
    @JsonSerialize(using = UsSerializer.class)
	public Us getUs() {
		return this.us;
	}

	public void setUs(Us us) {
		this.us = us;
	}

	@Column(name = "result", length = 150)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Column(name = "activist_id")
	public Integer getActivistId() {
		return this.activistId;
	}

	public void setActivistId(Integer activistId) {
		this.activistId = activistId;
	}

	@Column(name = "entry_point", nullable = false, length = 50)
	public String getEntryPoint() {
		return this.entryPoint;
	}

	public void setEntryPoint(String entryPoint) {
		this.entryPoint = entryPoint;
	}

	@Column(name = "provider", length = 100)
	public String getProvider() {
		return this.provider;
	}

	public void setProvider(String provider) {
		this.provider = provider;
	}

	@Column(name = "remarks", length = 250)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "created_by", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "updated_by", length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_updated", length = 19)
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	@Column(name = "offline_id", length = 45)
	public String getOfflineId() {
		return this.offlineId;
	}

	public void setOfflineId(String offlineId) {
		this.offlineId = offlineId;
	}
	
	public ObjectNode toObjectNode(String lastPulledAt) {
        ObjectMapper mapper = new ObjectMapper();
        ObjectNode beneficiaryIntervention = mapper.createObjectNode();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        if (offlineId != null) {
            beneficiaryIntervention.put("id", offlineId);
        } else {
            beneficiaryIntervention.put("id", id.toString());
        }

        if (dateUpdated == null || dateUpdated.after(dateCreated) || lastPulledAt == null || lastPulledAt.equals("null")) {
            beneficiaryIntervention.put("beneficiary_id", beneficiaries.getId());
            beneficiaryIntervention.put("sub_service_id", subServices.getId());
            beneficiaryIntervention.put("result", result);
            beneficiaryIntervention.put("date", dateFormat.format(id.getDate()));
            beneficiaryIntervention.put("us_id", us.getId());
            beneficiaryIntervention.put("result", result);
            beneficiaryIntervention.put("activist_id", activistId);
            beneficiaryIntervention.put("entry_point", entryPoint);
            beneficiaryIntervention.put("provider", provider);
            beneficiaryIntervention.put("remarks", remarks);
            beneficiaryIntervention.put("status", status);
            beneficiaryIntervention.put("online_id", id.toString()); // flag to control if entity is synchronized with the backend
        } else { // ensure online_id is updated first
            beneficiaryIntervention.put("online_id", id.toString());
        }
        return beneficiaryIntervention;
    }
	
	public void update(BeneficiaryInterventionSyncModel model, String timestamp) throws ParseException {
        Long t = Long.valueOf(timestamp);
        
        this.offlineId = model.getId();
        this.dateUpdated = new Date(t);
        this.beneficiaries.setId(model.getBeneficiary_id());
        this.subServices.setId(model.getSub_service_id());
        DateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");
        Date date1=dateFormatter.parse(model.getDate());  
        this.id.setDate(date1);;
        this.us = new Us(model.getUs_id());
        this.result = model.getResult();
        this.activistId = model.getActivist_id();
        this.entryPoint = model.getEntry_point();
        this.provider = model.getProvider();
        this.remarks = model.getRemarks();
        this.status = model.getStatus();
    }

}
