package dlt.dltbackendmaster.domain;
// Generated Jun 13, 2022, 9:37:47 AM by Hibernate Tools 5.2.12.Final

import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.datatype.jsr310.deser.LocalDateDeserializer;
import com.fasterxml.jackson.datatype.jsr310.ser.LocalDateSerializer;

/**
 * BeneficiariesInterventionsId generated by hbm2java
 */
@Embeddable
public class BeneficiariesInterventionsId implements java.io.Serializable {

	private static final long serialVersionUID = -3312323271412669443L;
	private int beneficiaryId;
	private int subServiceId;
	private LocalDate date;

	public BeneficiariesInterventionsId() {
	}

	public BeneficiariesInterventionsId(int beneficiaryId, int subServiceId, LocalDate date) {
		this.beneficiaryId = beneficiaryId;
		this.subServiceId = subServiceId;
		this.date = date;
	}

	@Column(name = "beneficiary_id", nullable = false)
	public int getBeneficiaryId() {
		return this.beneficiaryId;
	}

	public void setBeneficiaryId(int beneficiaryId) {
		this.beneficiaryId = beneficiaryId;
	}

	@Column(name = "sub_service_id", nullable = false)
	public int getSubServiceId() {
		return this.subServiceId;
	}

	public void setSubServiceId(int subServiceId) {
		this.subServiceId = subServiceId;
	}

	
	@Column(name = "date", nullable = false, length = 10)
	@JsonDeserialize(using = LocalDateDeserializer.class)
	@JsonSerialize(using = LocalDateSerializer.class)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
	@DateTimeFormat(pattern = "yyyy-MM-dd", iso = ISO.DATE)
	public LocalDate getDate() {
		return this.date;
	}

	public void setDate(LocalDate date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BeneficiariesInterventionsId))
			return false;
		BeneficiariesInterventionsId castOther = (BeneficiariesInterventionsId) other;

		return (this.getBeneficiaryId() == castOther.getBeneficiaryId())
				&& (this.getSubServiceId() == castOther.getSubServiceId())
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBeneficiaryId();
		result = 37 * result + this.getSubServiceId();
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return ""+beneficiaryId+","+subServiceId+","+date.toString();
	}
	
	

}
