package dlt.dltbackendmaster.domain;
// Generated Jun 13, 2022, 9:37:47 AM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;

import dlt.dltbackendmaster.domain.watermelondb.BeneficiarySyncModel;
import dlt.dltbackendmaster.serializers.DistrictSerializer;
import dlt.dltbackendmaster.serializers.LocalitySerializer;
import dlt.dltbackendmaster.serializers.NeighborhoodSerializer;
import dlt.dltbackendmaster.serializers.PartnersSerializer;
import dlt.dltbackendmaster.serializers.UsSerializer;

/**
 * Beneficiaries generated by hbm2java
 */
@Entity
@Table(name = "beneficiaries", catalog = "dreams_db", uniqueConstraints = @UniqueConstraint(columnNames = "nui"))
@NamedQueries({ @NamedQuery(name = "Beneficiary.findAll", query = "SELECT b FROM Beneficiaries b "
																+ " left join fetch b.neighborhood "
																+ " left join fetch b.partners "
																+ " left join fetch b.locality "
																+ " left join fetch b.us "
																+ " where b.status = 1 "
																+ " and b.nui like :searchNui "
																+ " and concat(b.name, \' \' ,b.surname) like concat('%',:searchName,'%') "
																+ " AND (:searchUserCreator IS NULL OR b.createdBy = :searchUserCreator OR b.updatedBy =:searchUserCreator) "
												                + " AND (:searchDistrict IS NULL OR b.district.id = :searchDistrict) "
																+ " order by b.id desc"
																+ ""),
                @NamedQuery(name = "Beneficiary.findByNui", query = "SELECT b FROM Beneficiaries b "
										                		+ " left join fetch b.neighborhood "
																+ " left join fetch b.partners "
																+ " left join fetch b.locality "
																+ " left join fetch b.us "
                												+ " where nui = :nui "
                												+ ""),
                @NamedQuery(name = "Beneficiary.findById", query = "SELECT b FROM Beneficiaries b "
										                		+ " left join fetch b.neighborhood "
																+ " left join fetch b.partners "
																+ " left join fetch b.locality "
																+ " left join fetch b.us "
																+ " where b.id = :id "
																+ ""),
                @NamedQuery(name = "Beneficiary.findByOfflineId", query = "SELECT b FROM Beneficiaries b "
										                		+ " left join fetch b.neighborhood "
																+ " left join fetch b.partners "
																+ " left join fetch b.locality "
																+ " left join fetch b.us "
                												+ " where b.offlineId = :offlineId "
                												+ ""),
                @NamedQuery(name = "Beneficiary.findByLocalities", query = "SELECT b FROM Beneficiaries b "
										                		+ " left join fetch b.neighborhood nb "
																+ " left join fetch b.partners "
																+ " left join fetch b.locality "
																+ " left join fetch b.us "
                												+ " where b.locality.id in (:localities) "
                												+ " and b.nui like :searchNui "
																+ " and concat(b.name, \' \' ,b.surname) like concat('%',:searchName,'%') "
                												+ " AND (:searchUserCreator IS NULL OR b.createdBy = :searchUserCreator OR b.updatedBy =:searchUserCreator) "
												                + " AND (:searchDistrict IS NULL OR b.district.id = :searchDistrict) "
                												+ " and b.status = 1 "
                												+ " order by b.id desc "
                												+ ""),
                @NamedQuery(name = "Beneficiary.findByLocalitiesOrReferenceNotifyTo", query = "SELECT b FROM Beneficiaries b "
										                		+ " left join fetch b.neighborhood nb "
																+ " left join fetch b.partners "
																+ " left join fetch b.locality l "
																+ " left join fetch b.us "
																+ " where (b.locality.id in (:localities) "	
																+ " or b.id in (SELECT r.beneficiaries.id from References r "
																+ "				where r.notifyTo.id = :userId)) "
																+ " and b.nui like :searchNui "
																+ " and concat(b.name, \' \' ,b.surname) like concat('%',:searchName,'%') "
																+ " AND (:searchUserCreator IS NULL OR b.createdBy = :searchUserCreator OR b.updatedBy =:searchUserCreator) "
												                + " AND (:searchDistrict IS NULL OR b.district.id = :searchDistrict) "
																+ " and b.status = 1 "
																+ " order by b.id desc "
																+ ""),
                @NamedQuery(name = "Beneficiary.findByDistricts", query = "SELECT b FROM Beneficiaries b "
										                		+ " left join fetch b.neighborhood nb "
																+ " left join fetch b.partners "
																+ " left join fetch b.locality "
																+ " left join fetch b.us "
                												+ " where b.district.id in (:districts) "
                												+ " and b.nui like :searchNui "
																+ " and concat(b.name, \' \' ,b.surname) like concat('%',:searchName,'%') "
                												+ " AND (:searchUserCreator IS NULL OR b.createdBy = :searchUserCreator OR b.updatedBy =:searchUserCreator) "
												                + " AND (:searchDistrict IS NULL OR b.district.id = :searchDistrict) "
                												+ " and b.status = 1 "
                												+ " order by b.id desc "
                                                                + ""),
                @NamedQuery(name = "Beneficiary.findByProvinces", query = "SELECT b FROM Beneficiaries b "
										                		+ " left join fetch b.neighborhood nb "
																+ " left join fetch b.partners "
																+ " left join fetch b.locality "
																+ " left join fetch b.us "
                												+ " where b.district.province.id in (:provinces) "
                												+ " and b.nui like :searchNui "
																+ " and concat(b.name, \' \' ,b.surname) like concat('%',:searchName,'%') "
                												+ " AND (:searchUserCreator IS NULL OR b.createdBy = :searchUserCreator OR b.updatedBy =:searchUserCreator) "
												                + " AND (:searchDistrict IS NULL OR b.district.id = :searchDistrict) "
                												+ " and b.status = 1 "
                												+ " order by b.id desc "
                												+ ""),
                @NamedQuery(name = "Beneficiary.findByDateCreated",query = "select b from Beneficiaries b "
										                		+ " left join fetch b.neighborhood nb "
																+ " left join fetch b.partners "
																+ " left join fetch b.locality "
																+ " left join fetch b.us "
                            									+ " where b.dateUpdated is null and b.dateCreated > :lastpulledat "
                            									+ ""),
                @NamedQuery(name = "Beneficiary.findByDateUpdated",query = "select b from Beneficiaries b "
										                		+ " left join fetch b.neighborhood "
																+ " left join fetch b.partners "
																+ " left join fetch b.locality "
																+ " left join fetch b.us "
                            									+ " where (b.dateUpdated >= :lastpulledat) "
                            									+ " or (b.dateUpdated >= :lastpulledat "
                            									+ " and b.dateCreated = b.dateUpdated)"),
                @NamedQuery(name = "Beneficiary.findByIdsAndDateUpdated",query = "select b from Beneficiaries b "
										                		+ " left join fetch b.neighborhood "
																+ " left join fetch b.partners "
																+ " left join fetch b.locality "
																+ " left join fetch b.us "
																+ " where b.id in :beneficiariesIds "
																+ " and b.dateCreated < :lastpulledat "
																+ " and b.dateUpdated >= :lastpulledat"
																+ ""),
                @NamedQuery(name = "Beneficiary.findCountByLocalities", query = "SELECT count(b.id) as total FROM Beneficiaries b "
																+ " where b.locality.id in (:localities) "
																+ " and b.status = 1 "
																+ ""),              
                @NamedQuery(name = "Beneficiary.findCountByLocalitiesOrReferenceNotifyTo", query = "SELECT count(b.id) as total FROM Beneficiaries b "
																+ " where (b.locality.id in (:localities) "	
																+ " or b.id in (SELECT r.beneficiaries.id from References r "
																+ "				where r.notifyTo.id = :userId)) "
																+ " and b.status = 1 "
																+ " and b.nui like :searchNui "
																+ " and concat(b.name, \' \' ,b.surname) like concat('%',:searchName,'%') "
                												+ " AND (:searchUserCreator IS NULL OR b.createdBy = :searchUserCreator OR b.updatedBy =:searchUserCreator) "
												                + " AND (:searchDistrict IS NULL OR b.district.id = :searchDistrict) "
																+ ""),
                @NamedQuery(name = "Beneficiary.findCountByDistricts", query = "SELECT count(b.id) as total FROM Beneficiaries b "
																+ " where b.district.id in (:districts)"
																+ " and b.status = 1 "
																+ " and b.nui like :searchNui "
																+ " and concat(b.name, \' \' ,b.surname) like concat('%',:searchName,'%') "
                												+ " AND (:searchUserCreator IS NULL OR b.createdBy = :searchUserCreator OR b.updatedBy =:searchUserCreator) "
												                + " AND (:searchDistrict IS NULL OR b.district.id = :searchDistrict) "
																+ ""),
                @NamedQuery(name = "Beneficiary.findCountByDistrictAndGender", query = "SELECT count(b.id) as total FROM Beneficiaries b "
																+ " where b.district.id = :district "
																+ " and b.gender = :gender "
																+ " and b.status = 1 "
																+ ""),
				@NamedQuery(name = "Beneficiary.findCountByProvinces", query = "SELECT count(b.id) as total FROM Beneficiaries b "
																+ " where b.district.province.id in (:provinces) "
																+ " and b.status = 1 "
																+ " and b.nui like :searchNui "
																+ " and concat(b.name, \' \' ,b.surname) like concat('%',:searchName,'%') "
                												+ " AND (:searchUserCreator IS NULL OR b.createdBy = :searchUserCreator OR b.updatedBy =:searchUserCreator) "
												                + " AND (:searchDistrict IS NULL OR b.district.id = :searchDistrict) "
																+ ""),
				@NamedQuery(name = "Beneficiary.findCountAll", query = "SELECT count(b.id) as total FROM Beneficiaries b "
																+ " where b.status = 1 "
																+ " and b.nui like :searchNui "
																+ " and concat(b.name, \' \' ,b.surname) like concat('%',:searchName,'%') "
                												+ " AND (:searchUserCreator IS NULL OR b.createdBy = :searchUserCreator OR b.updatedBy =:searchUserCreator) "
												                + " AND (:searchDistrict IS NULL OR b.district.id = :searchDistrict) "
																+ ""),
				@NamedQuery(name = "Beneficiary.findByReferenceNotifyToOrBeneficiaryCreatedBy", query = "SELECT  b FROM  Beneficiaries b "
																+ " left join  b.neighborhood nb "
																+ " left join  b.partners "
																+ " left join  b.locality "
																+ " left join  b.us "
																+ " where b.status = 1 "
                                                                + " and (b.createdBy = :userId "	
																+ " or   b.id in "
																+ "	("
																+ "		SELECT r.beneficiaries.id from References r"
												                + " 	where r.status in (0,1) "
												                + " 	and r.notifyTo.id = :userId"
												                + "	)) "    											     
												                ),
				@NamedQuery(name = "Beneficiary.findByReferenceNotifyToOrBeneficiaryCreatedByAndDateCreated", query = "SELECT  b FROM  Beneficiaries b "
																+ " left join  b.neighborhood nb "
																+ " left join  b.partners "
																+ " left join  b.locality "
																+ " left join  b.us "
																+ " where b.status = 1 "
										                        + " and (b.createdBy = :userId "
										                        + " and b.dateCreated >= :lastpulledat"	
																+ " or   b.id in "
																+ "	("
																+ "		SELECT r.beneficiaries.id from References r"
												                + " 	where r.status in (0,1) "
												                + " 	and r.notifyTo.id = :userId"
												                + " 	and r.dateCreated >= :lastpulledat"
												                + "	))"
										                        
												                ),
				@NamedQuery(name = "Beneficiary.findByReferenceNotifyToOrBeneficiaryCreatedByAndDateUpdated", query = "SELECT  b FROM  Beneficiaries b "
																+ " left join  b.neighborhood nb "
																+ " left join  b.partners "
																+ " left join  b.locality "
																+ " left join  b.us "
																+ " where (b.createdBy = :userId "
																+ " or   b.id in "
																+ " ("
																+ "		SELECT r.beneficiaries.id from References r"
												                + " 	where r.status in (0,1) "
												                + " 	and r.notifyTo.id = :userId "
												                + "		and r.dateCreated >= :lastpulledat"
												                + "	))"
												                + " and b.dateCreated < :lastpulledat "
												                + " and b.dateUpdated >= :lastpulledat "
												                ),
				@NamedQuery(name = "Beneficiary.getBeneficiariesByNui", query = "SELECT  b FROM  Beneficiaries b "
																+ " left join  b.neighborhood nb "
																+ " left join  b.partners "
																+ " left join  b.locality "
																+ " left join  b.us "
																+ " where b.nui =:nui "
																+ " and b.locality.id in :localitiesIds "												         											     
												                ),
				@NamedQuery(name = "Beneficiary.findByIds", query = "SELECT b FROM Beneficiaries b "
																+ " left join fetch b.neighborhood "
																+ " left join fetch b.partners "
																+ " left join fetch b.locality "
																+ " left join fetch b.us "
																+ " where b.status = 1 "
																+ " and b.id in :ids "
																+ " order by b.id desc"
																+ ""),
				@NamedQuery(name = "Beneficiary.getBeneficiariesByPartnerId", query = "SELECT  b FROM  Beneficiaries b "
																+ " where b.partnerId = :partnerId "),
				@NamedQuery(name = "Beneficiary.findByNameAndDateOfBirthAndLocality", query = "SELECT  b FROM  Beneficiaries b "
																+ " left join fetch b.neighborhood "
																+ " left join fetch b.partners "
																+ " left join fetch b.locality "
																+ " left join fetch b.us "
																+ " where b.name =:name "															
																+ " and b.dateOfBirth =:dateOfBirth "
																+ " and b.locality.id =:locality "												         											     
												                ),
				
				
				@NamedQuery(name = "Beneficiary.findAny", query = "SELECT b FROM Beneficiaries b "
										+ " left join fetch b.neighborhood "
										+ " left join fetch b.partners "
										+ " left join fetch b.locality "
										+ " left join fetch b.us "
										+ " where b.status IN (0,1) "
										+ " and b.nui like :searchNui "
										+ " and concat(b.name, \' \' ,b.surname) like concat('%',:searchName,'%') "
										+ " AND (:searchUserCreator IS NULL OR b.createdBy = :searchUserCreator OR b.updatedBy =:searchUserCreator) "
						                + " AND (:searchDistrict IS NULL OR b.district.id = :searchDistrict) "
										+ " order by b.id desc"
										+ ""),
				@NamedQuery(name = "Beneficiary.findAnyByLocalitiesOrReferenceNotifyTo", query = "SELECT b FROM Beneficiaries b "
				                		+ " left join fetch b.neighborhood nb "
										+ " left join fetch b.partners "
										+ " left join fetch b.locality l "
										+ " left join fetch b.us "
										+ " where (b.locality.id in (:localities) "	
										+ " or b.id in (SELECT r.beneficiaries.id from References r "
										+ "				where r.notifyTo.id = :userId)) "
										+ " and b.nui like :searchNui "
										+ " and concat(b.name, \' \' ,b.surname) like concat('%',:searchName,'%') "
										+ " AND (:searchUserCreator IS NULL OR b.createdBy = :searchUserCreator OR b.updatedBy =:searchUserCreator) "
						                + " AND (:searchDistrict IS NULL OR b.district.id = :searchDistrict) "
										+ " and b.status IN (0,1) "
										+ " order by b.id desc "
										+ ""),
				@NamedQuery(name = "Beneficiary.findAnyByDistricts", query = "SELECT b FROM Beneficiaries b "
				                		+ " left join fetch b.neighborhood nb "
										+ " left join fetch b.partners "
										+ " left join fetch b.locality "
										+ " left join fetch b.us "
										+ " where b.district.id in (:districts) "
										+ " and b.nui like :searchNui "
										+ " and concat(b.name, \' \' ,b.surname) like concat('%',:searchName,'%') "
										+ " AND (:searchUserCreator IS NULL OR b.createdBy = :searchUserCreator OR b.updatedBy =:searchUserCreator) "
						                + " AND (:searchDistrict IS NULL OR b.district.id = :searchDistrict) "
										+ " and b.status IN (0,1) "
										+ " order by b.id desc "
				                        + ""),
				@NamedQuery(name = "Beneficiary.findAnyByProvinces", query = "SELECT b FROM Beneficiaries b "
				                		+ " left join fetch b.neighborhood nb "
										+ " left join fetch b.partners "
										+ " left join fetch b.locality "
										+ " left join fetch b.us "
										+ " where b.district.province.id in (:provinces) "
										+ " and b.nui like :searchNui "
										+ " and concat(b.name, \' \' ,b.surname) like concat('%',:searchName,'%') "
										+ " AND (:searchUserCreator IS NULL OR b.createdBy = :searchUserCreator OR b.updatedBy =:searchUserCreator) "
						                + " AND (:searchDistrict IS NULL OR b.district.id = :searchDistrict) "
										+ " and b.status IN (0,1) "
										+ " order by b.id desc "
										+ ""),
				@NamedQuery(name = "Beneficiary.findByIdAndBeforeCompletedAServiceButNotFullPrimaryPackage", query = "SELECT b FROM Beneficiaries b where b.id = :beneficiary_id and b.completionStatus < 1"),
				@NamedQuery(name = "Beneficiary.findByIdAndBeforeCompletedExactlyPrimaryPackage", query = "SELECT b FROM Beneficiaries b where b.id = :beneficiary_id and b.completionStatus < 2"),
				@NamedQuery(name = "Beneficiary.findByIdAndBeforeCompletedPrimaryPackageAndAdditionalServices", query = "SELECT b FROM Beneficiaries b where b.id = :beneficiary_id and b.completionStatus < 3"), 
})
public class Beneficiaries implements java.io.Serializable
{
    private static final long serialVersionUID = -8649443166960196872L;
    
    private Integer id;
    private Neighborhood neighborhood;
    private Partners partners;
    private Locality locality;
    private District district;
    private Us us;
    private String nui;
    private String surname;
    private String name;
    private String nickName;
    private Date dateOfBirth;
    private char gender;
    private String address;
    private String phoneNumber;
    private String EMail;
    private Date enrollmentDate;
    private Integer via;
    private Integer nationality;
    private Integer partnerId;
    private String partnerNUI;
    private String entryPoint;
    private String vbltLivesWith;
    private Byte vbltIsOrphan;
    private Byte vbltIsStudent;
    private Integer vbltSchoolGrade;
    private String vbltSchoolName;
    private Byte vbltIsDeficient;
    private String vbltDeficiencyType;
    private Byte vbltMarriedBefore;
    private Byte vbltPregnantBefore;
    private Byte vbltChildren;
    private Byte vbltPregnantOrBreastfeeding;
    private String vbltIsEmployed;
    private Byte vbltIdp;
    private String vbltTestedHiv;
    private Byte vbltSexuallyActive;
    private Byte vbltPregnantOrHasChildren;
    private Byte vbltMultiplePartners;
    private Byte vbltIsMigrant;
    private Byte vbltTraffickingVictim;
    private Byte vbltSexualExploitation;
    private String vbltSexploitationTime;
    private Byte vbltVbgVictim;
    private String vbltVbgType;
    private String vbltVbgTime;
    private Byte vbltAlcoholDrugsUse;
    private Byte vbltStiHistory;
    private Byte vbltSexWorker;
    private Byte vbltHouseSustainer;
    private int status;
    private Integer clinicalInterventions;
    private Integer communityInterventions;
    private int createdBy;
    private Date dateCreated;
    private Integer updatedBy;
    private Date dateUpdated;
    private String offlineId;
    private Set<VulnerabilityHistory> vulnerabilityHistories = new HashSet<VulnerabilityHistory>(0);
    private Set<BeneficiariesInterventions> beneficiariesInterventionses = new HashSet<BeneficiariesInterventions>(0);
    private Set<References> referenceses = new HashSet<References>(0);
	private int completionStatus;
	
	public Beneficiaries() {}

    public Beneficiaries(Neighborhood neighborhood, Us us, String nui, String surname, String name, String nickName,
                         Date dateOfBirth, char gender, Date enrollmentDate, Integer nationality, String entryPoint,
                         int status, int createdBy, Date dateCreated) {
        this.neighborhood = neighborhood;
        this.us = us;
        this.nui = nui;
        this.surname = surname;
        this.name = name;
        this.nickName = nickName;
        this.dateOfBirth = dateOfBirth;
        this.gender = gender;
        this.enrollmentDate = enrollmentDate;
        this.nationality = nationality;
        this.entryPoint = entryPoint;
        this.status = status;
        this.createdBy = createdBy;
        this.dateCreated = dateCreated;
        this.clinicalInterventions = 0;
        this.communityInterventions = 0;
    }

    public Beneficiaries(Neighborhood neighborhood, Partners partners, Locality locality, District district_id, Us us, String nui, String surname, String name,
                         String nickName, Date dateOfBirth, char gender, String address,
                         String phoneNumber, String EMail, Date enrollmentDate, Integer via, Integer nationality,
                         Integer partnerId, String entryPoint, String vbltLivesWith, Byte vbltIsOrphan,
                         Byte vbltIsStudent, Integer vbltSchoolGrade, String vbltSchoolName, Byte vbltIsDeficient,
                         String vbltDeficiencyType, Byte vbltMarriedBefore, Byte vbltPregnantBefore, Byte vbltChildren,
                         Byte vbltPregnantOrBreastfeeding, String vbltIsEmployed, String vbltTestedHiv, Byte vbltIdp,
                         Byte vbltSexuallyActive, Byte vbltPregnantOrHasChildren, Byte vbltMultiplePartners, Byte vbltIsMigrant,
                         Byte vbltTraffickingVictim, Byte vbltSexualExploitation, String vbltSexploitationTime,
                         Byte vbltVbgVictim, String vbltVbgType, String vbltVbgTime, Byte vbltAlcoholDrugsUse,
                         Byte vbltStiHistory, Byte vbltSexWorker, Byte vbltHouseSustainer, int status, int createdBy,
                         Date dateCreated, Integer updatedBy, Date dateUpdated, String offlineId,
                         Set<VulnerabilityHistory> vulnerabilityHistories,
                         Set<BeneficiariesInterventions> beneficiariesInterventionses, Set<References> referenceses) {
        this.neighborhood = neighborhood;
        this.partners = partners;
        this.locality = locality;
        this.district = district_id;
        this.us = us;
        this.nui = nui;
        this.surname = surname;
        this.name = name;
        this.nickName = nickName;
        this.dateOfBirth = dateOfBirth;
        this.gender = gender;
        this.address = address;
        this.phoneNumber = phoneNumber;
        this.EMail = EMail;
        this.enrollmentDate = enrollmentDate;
        this.via = via;
        this.nationality = nationality;
        this.partnerId = partnerId;
        this.entryPoint = entryPoint;
        this.vbltLivesWith = vbltLivesWith;
        this.vbltIsOrphan = vbltIsOrphan;
        this.vbltIsStudent = vbltIsStudent;
        this.vbltSchoolGrade = vbltSchoolGrade;
        this.vbltSchoolName = vbltSchoolName;
        this.vbltIsDeficient = vbltIsDeficient;
        this.vbltDeficiencyType = vbltDeficiencyType;
        this.vbltMarriedBefore = vbltMarriedBefore;
        this.vbltPregnantBefore = vbltPregnantBefore;
        this.vbltChildren = vbltChildren;
        this.vbltPregnantOrBreastfeeding = vbltPregnantOrBreastfeeding;
        this.vbltIsEmployed = vbltIsEmployed;
        this.vbltTestedHiv = vbltTestedHiv;
        this.vbltIdp = vbltIdp;
        this.vbltSexuallyActive = vbltSexuallyActive;
        this.vbltPregnantOrHasChildren = vbltPregnantOrHasChildren;
        this.vbltMultiplePartners = vbltMultiplePartners;
        this.vbltIsMigrant = vbltIsMigrant;
        this.vbltTraffickingVictim = vbltTraffickingVictim;
        this.vbltSexualExploitation = vbltSexualExploitation;
        this.vbltSexploitationTime = vbltSexploitationTime;
        this.vbltVbgVictim = vbltVbgVictim;
        this.vbltVbgType = vbltVbgType;
        this.vbltVbgTime = vbltVbgTime;
        this.vbltAlcoholDrugsUse = vbltAlcoholDrugsUse;
        this.vbltStiHistory = vbltStiHistory;
        this.vbltSexWorker = vbltSexWorker;
        this.vbltHouseSustainer = vbltHouseSustainer;
        this.status = status;
        this.createdBy = createdBy;
        this.dateCreated = dateCreated;
        this.updatedBy = updatedBy;
        this.dateUpdated = dateUpdated;
        this.offlineId = offlineId;
        this.vulnerabilityHistories = vulnerabilityHistories;
        this.beneficiariesInterventionses = beneficiariesInterventionses;
        this.referenceses = referenceses;
        this.clinicalInterventions = 0;
        this.communityInterventions = 0;
    }

    public Beneficiaries(BeneficiarySyncModel model, String timestamp) {
        this.nui = model.getNui();
        this.surname = model.getSurname();
        this.nickName = model.getNick_name();
        this.name = model.getName();
        this.partners = new Partners(model.getOrganization_id());
        this.locality = new Locality(model.getLocality_id());
        this.district = new District(model.getDistrict_id());
        this.dateOfBirth = model.getDate_of_birth();
        this.dateCreated = model.getDate_created();
        this.dateUpdated = model.getDate_updated();
        this.gender = model.getGender();
        this.address = model.getAddress();
        this.phoneNumber = model.getPhone_number();
        this.EMail = model.getE_mail();
        this.via = model.getVia();
        this.nationality = 1;
        this.enrollmentDate = model.getEnrollment_date();
        this.entryPoint = model.getEntry_point();
        this.neighborhood = new Neighborhood(model.getNeighborhood_id());
        this.us = new Us(model.getUs_id());
        this.offlineId = model.getId();
        this.vbltLivesWith = model.getVblt_lives_with();
        this.vbltIsOrphan = model.getVblt_is_orphan();
        this.vbltIsStudent = model.getVblt_is_student();
        this.vbltSchoolGrade = model.getVblt_school_grade();
        this.vbltSchoolName = model.getVblt_school_name();
        this.vbltIsDeficient = model.getVblt_is_deficient();
        this.vbltDeficiencyType = model.getVblt_deficiency_type();
        this.vbltMarriedBefore = model.getVblt_married_before();
        this.vbltPregnantBefore = model.getVblt_pregnant_before();
        this.vbltChildren = model.getVblt_children();
        this.vbltPregnantOrBreastfeeding = model.getVblt_pregnant_or_breastfeeding();
        this.vbltIsEmployed = model.getVblt_is_employed();
        this.vbltIdp = model.getVblt_idp();
        this.vbltTestedHiv = model.getVblt_tested_hiv();
        this.vbltSexuallyActive = model.getVblt_sexually_active();
        this.vbltPregnantOrHasChildren = model.getVblt_pregnant_or_has_children();
        this.vbltMultiplePartners = model.getVblt_multiple_partners();
        this.vbltIsMigrant = model.getVblt_is_migrant();
        this.vbltTraffickingVictim = model.getVblt_trafficking_victim();
        this.vbltSexualExploitation = model.getVblt_sexual_exploitation();
        this.vbltSexploitationTime = model.getVblt_sexploitation_time();
        this.vbltVbgVictim = model.getVblt_vbg_victim();
        this.vbltVbgType = model.getVblt_vbg_type();
        this.vbltVbgTime = model.getVblt_vbg_time();
        this.vbltAlcoholDrugsUse = model.getVblt_alcohol_drugs_use();
        this.vbltStiHistory = model.getVblt_sti_history();
        this.vbltSexWorker = model.getVblt_sex_worker();
        this.vbltHouseSustainer = model.getVblt_house_sustainer();
        this.status = Integer.valueOf(model.getStatus());
        this.clinicalInterventions = 0;
        this.communityInterventions = 0;
    }

    public Beneficiaries(BeneficiarySyncModel model) {
        this.nui = model.getNui();
        this.surname = model.getSurname();
        this.nickName = model.getNick_name();
        this.name = model.getName();
        this.partners = new Partners(model.getOrganization_id());
        this.locality = new Locality(model.getLocality_id());
        this.district = new District(model.getDistrict_id());
        this.dateOfBirth = model.getDate_of_birth();
        this.dateCreated = model.getDate_created();
        this.dateUpdated = model.getDate_updated();
        this.gender = model.getGender();
        this.address = model.getAddress();
        this.phoneNumber = model.getPhone_number();
        this.EMail = model.getE_mail();
        this.via = model.getVia();
        this.entryPoint = model.getEntry_point();
        this.neighborhood = new Neighborhood(model.getNeighborhood_id());
        this.us = new Us(model.getUs_id());
        this.offlineId = model.getId();
        this.vbltLivesWith = model.getVblt_lives_with();
        this.vbltIsOrphan = model.getVblt_is_orphan();
        this.vbltIsStudent = model.getVblt_is_student();
        this.vbltSchoolGrade = model.getVblt_school_grade();
        this.vbltSchoolName = model.getVblt_school_name();
        this.vbltIsDeficient = model.getVblt_is_deficient();
        this.vbltDeficiencyType = model.getVblt_deficiency_type();
        this.vbltMarriedBefore = model.getVblt_married_before();
        this.vbltPregnantBefore = model.getVblt_pregnant_before();
        this.vbltChildren = model.getVblt_children();
        this.vbltPregnantOrBreastfeeding = model.getVblt_pregnant_or_breastfeeding();
        this.vbltIsEmployed = model.getVblt_is_employed();
        this.vbltTestedHiv = model.getVblt_tested_hiv();
        this.vbltSexuallyActive = model.getVblt_sexually_active();
        this.vbltMultiplePartners = model.getVblt_multiple_partners();
        this.vbltIsMigrant = model.getVblt_is_migrant();
        this.vbltTraffickingVictim = model.getVblt_trafficking_victim();
        this.vbltSexualExploitation = model.getVblt_sexual_exploitation();
        this.vbltSexploitationTime = model.getVblt_sexploitation_time();
        this.vbltVbgVictim = model.getVblt_vbg_victim();
        this.vbltVbgType = model.getVblt_vbg_type();
        this.vbltVbgTime = model.getVblt_vbg_time();
        this.vbltAlcoholDrugsUse = model.getVblt_alcohol_drugs_use();
        this.vbltStiHistory = model.getVblt_sti_history();
        this.vbltSexWorker = model.getVblt_sex_worker();
        this.vbltHouseSustainer = model.getVblt_house_sustainer();
        this.status = Integer.valueOf(model.getStatus());
        this.clinicalInterventions = 0;
        this.communityInterventions = 0;
    }

    public Beneficiaries(Integer id) {
        this.id = id;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "neighbourhood_id", nullable = true)
	@JsonSerialize(using = NeighborhoodSerializer.class)
    public Neighborhood getNeighborhood() {
        return this.neighborhood;
    }

    public void setNeighborhood(Neighborhood neighborhood) {
        this.neighborhood = neighborhood;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "organization_id")
	@JsonSerialize(using = PartnersSerializer.class)
    public Partners getPartners() {
        return this.partners;
    }

    public void setPartners(Partners partners) {
        this.partners = partners;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "locality_id")
	@JsonSerialize(using = LocalitySerializer.class)
    public Locality getLocality() {
        return this.locality;
    }

    public void setLocality(Locality locality) {
        this.locality = locality;
    }

    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "district_id")
	@JsonSerialize(using = DistrictSerializer.class)
    public District getDistrict() {
		return district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}

	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "us_id")
	@JsonSerialize(using = UsSerializer.class)
    public Us getUs() {
        return this.us;
    }

    public void setUs(Us us) {
        this.us = us;
    }

    @Column(name = "nui", unique = true, nullable = false, length = 50)
    public String getNui() {
        return this.nui;
    }

    public void setNui(String nui) {
        this.nui = nui;
    }

    @Column(name = "surname", nullable = false, length = 50)
    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    @Column(name = "name", nullable = false, length = 150)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "nick_name", length = 50)
    public String getNickName() {
        return this.nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "date_of_birth", nullable = true, length = 10)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    @Column(name = "gender", nullable = false, length = 1)
    public char getGender() {
        return this.gender;
    }

    public void setGender(char gender) {
        this.gender = gender;
    }

    @Column(name = "address", length = 250)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "phone_number", length = 50)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Column(name = "e_mail", length = 150)
    public String getEMail() {
        return this.EMail;
    }

    public void setEMail(String EMail) {
        this.EMail = EMail;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "enrollment_date", length = 10)
    public Date getEnrollmentDate() {
        return enrollmentDate;
    }

    public void setEnrollmentDate(Date enrollmentDate) {
        this.enrollmentDate = enrollmentDate;
    }

    @Column(name = "via")
    public Integer getVia() {
        return this.via;
    }

    public void setVia(Integer via) {
        this.via = via;
    }

    @Column(name = "partner_id")
    public Integer getPartnerId() {
        return this.partnerId;
    }

    public void setPartnerId(Integer partnerId) {
        this.partnerId = partnerId;
    }

    @Transient
    public String getPartnerNUI() {
        return partnerNUI;
    }

    public void setPartnerNUI(String partnerNUI) {
        this.partnerNUI = partnerNUI;
    }

    @Column(name = "nationality")
    public Integer getNationality() {
        return nationality;
    }

    public void setNationality(Integer nationality) {
        this.nationality = nationality;
    }

    @Column(name = "entry_point", nullable = false, length = 50)
    public String getEntryPoint() {
        return this.entryPoint;
    }

    public void setEntryPoint(String entryPoint) {
        this.entryPoint = entryPoint;
    }

    @Column(name = "vblt_lives_with", length = 254)
    public String getVbltLivesWith() {
        return this.vbltLivesWith;
    }

    public void setVbltLivesWith(String vbltLivesWith) {
        this.vbltLivesWith = vbltLivesWith;
    }

    @Column(name = "vblt_is_orphan")
    public Byte getVbltIsOrphan() {
        return this.vbltIsOrphan;
    }

    public void setVbltIsOrphan(Byte vbltIsOrphan) {
        this.vbltIsOrphan = vbltIsOrphan;
    }

    @Column(name = "vblt_is_student")
    public Byte getVbltIsStudent() {
        return this.vbltIsStudent;
    }

    public void setVbltIsStudent(Byte vbltIsStudent) {
        this.vbltIsStudent = vbltIsStudent;
    }

    @Column(name = "vblt_school_grade")
    public Integer getVbltSchoolGrade() {
        return this.vbltSchoolGrade;
    }

    public void setVbltSchoolGrade(Integer vbltSchoolGrade) {
        this.vbltSchoolGrade = vbltSchoolGrade;
    }

    @Column(name = "vblt_school_name", length = 45)
    public String getVbltSchoolName() {
        return this.vbltSchoolName;
    }

    public void setVbltSchoolName(String vbltSchoolName) {
        this.vbltSchoolName = vbltSchoolName;
    }

    @Column(name = "vblt_is_deficient")
    public Byte getVbltIsDeficient() {
        return this.vbltIsDeficient;
    }

    public void setVbltIsDeficient(Byte vbltIsDeficient) {
        this.vbltIsDeficient = vbltIsDeficient;
    }

    @Column(name = "vblt_deficiency_type", length = 45)
    public String getVbltDeficiencyType() {
        return this.vbltDeficiencyType;
    }

    public void setVbltDeficiencyType(String vbltDeficiencyType) {
        this.vbltDeficiencyType = vbltDeficiencyType;
    }

    @Column(name = "vblt_married_before")
    public Byte getVbltMarriedBefore() {
        return this.vbltMarriedBefore;
    }

    public void setVbltMarriedBefore(Byte vbltMarriedBefore) {
        this.vbltMarriedBefore = vbltMarriedBefore;
    }

    @Column(name = "vblt_pregnant_before")
    public Byte getVbltPregnantBefore() {
        return this.vbltPregnantBefore;
    }

    public void setVbltPregnantBefore(Byte vbltPregnantBefore) {
        this.vbltPregnantBefore = vbltPregnantBefore;
    }

    @Column(name = "vblt_children")
    public Byte getVbltChildren() {
        return this.vbltChildren;
    }

    public void setVbltChildren(Byte vbltChildren) {
        this.vbltChildren = vbltChildren;
    }

    @Column(name = "vblt_pregnant_or_breastfeeding")
    public Byte getVbltPregnantOrBreastfeeding() {
        return this.vbltPregnantOrBreastfeeding;
    }

    public void setVbltPregnantOrBreastfeeding(Byte vbltPregnantOrBreastfeeding) {
        this.vbltPregnantOrBreastfeeding = vbltPregnantOrBreastfeeding;
    }

    @Column(name = "vblt_is_employed", length = 254)
    public String getVbltIsEmployed() {
        return this.vbltIsEmployed;
    }

    public void setVbltIsEmployed(String vbltIsEmployed) {
        this.vbltIsEmployed = vbltIsEmployed;
    }

    public void setVbltTestedHiv(String vbltTestedHiv) {
        this.vbltTestedHiv = vbltTestedHiv;
    }

    @Column(name = "vblt_idp")
    public Byte getVbltIdp() {
		return vbltIdp;
	}

	public void setVbltIdp(Byte vbltIdp) {
		this.vbltIdp = vbltIdp;
	}

    @Column(name = "vblt_tested_hiv", length = 254)
    public String getVbltTestedHiv() {
        return this.vbltTestedHiv;
    }

	@Column(name = "vblt_sexually_active")
    public Byte getVbltSexuallyActive() {
        return this.vbltSexuallyActive;
    }

    public void setVbltSexuallyActive(Byte vbltSexuallyActive) {
        this.vbltSexuallyActive = vbltSexuallyActive;
    }

    @Column(name = "vblt_pregnant_or_has_children")
    public Byte getVbltPregnantOrHasChildren() {
		return vbltPregnantOrHasChildren;
	}

	public void setVbltPregnantOrHasChildren(Byte vbltPregnantOrHasChildren) {
		this.vbltPregnantOrHasChildren = vbltPregnantOrHasChildren;
	}

	@Column(name = "vblt_multiple_partners")
    public Byte getVbltMultiplePartners() {
        return this.vbltMultiplePartners;
    }

    public void setVbltMultiplePartners(Byte vbltMultiplePartners) {
        this.vbltMultiplePartners = vbltMultiplePartners;
    }

    @Column(name = "vblt_is_migrant")
    public Byte getVbltIsMigrant() {
        return this.vbltIsMigrant;
    }

    public void setVbltIsMigrant(Byte vbltIsMigrant) {
        this.vbltIsMigrant = vbltIsMigrant;
    }

    @Column(name = "vblt_trafficking_victim")
    public Byte getVbltTraffickingVictim() {
        return this.vbltTraffickingVictim;
    }

    public void setVbltTraffickingVictim(Byte vbltTraffickingVictim) {
        this.vbltTraffickingVictim = vbltTraffickingVictim;
    }

    @Column(name = "vblt_sexual_exploitation")
    public Byte getVbltSexualExploitation() {
        return this.vbltSexualExploitation;
    }

    public void setVbltSexualExploitation(Byte vbltSexualExploitation) {
        this.vbltSexualExploitation = vbltSexualExploitation;
    }

    @Column(name = "vblt_sexploitation_time", length = 45)
    public String getVbltSexploitationTime() {
        return this.vbltSexploitationTime;
    }

    public void setVbltSexploitationTime(String vbltSexploitationTime) {
        this.vbltSexploitationTime = vbltSexploitationTime;
    }

    @Column(name = "vblt_vbg_victim")
    public Byte getVbltVbgVictim() {
        return this.vbltVbgVictim;
    }

    public void setVbltVbgVictim(Byte vbltVbgVictim) {
        this.vbltVbgVictim = vbltVbgVictim;
    }

    @Column(name = "vblt_vbg_type", length = 45)
    public String getVbltVbgType() {
        return this.vbltVbgType;
    }

    public void setVbltVbgType(String vbltVbgType) {
        this.vbltVbgType = vbltVbgType;
    }

    @Column(name = "vblt_vbg_time", length = 45)
    public String getVbltVbgTime() {
        return this.vbltVbgTime;
    }

    public void setVbltVbgTime(String vbltVbgTime) {
        this.vbltVbgTime = vbltVbgTime;
    }

    @Column(name = "vblt_alcohol_drugs_use")
    public Byte getVbltAlcoholDrugsUse() {
        return this.vbltAlcoholDrugsUse;
    }

    public void setVbltAlcoholDrugsUse(Byte vbltAlcoholDrugsUse) {
        this.vbltAlcoholDrugsUse = vbltAlcoholDrugsUse;
    }

    @Column(name = "vblt_sti_history")
    public Byte getVbltStiHistory() {
        return this.vbltStiHistory;
    }

    public void setVbltStiHistory(Byte vbltStiHistory) {
        this.vbltStiHistory = vbltStiHistory;
    }

    @Column(name = "vblt_sex_worker")
    public Byte getVbltSexWorker() {
        return this.vbltSexWorker;
    }

    public void setVbltSexWorker(Byte vbltSexWorker) {
        this.vbltSexWorker = vbltSexWorker;
    }

    @Column(name = "vblt_house_sustainer")
    public Byte getVbltHouseSustainer() {
        return this.vbltHouseSustainer;
    }

    public void setVbltHouseSustainer(Byte vbltHouseSustainer) {
        this.vbltHouseSustainer = vbltHouseSustainer;
    }

    @Column(name = "status", nullable = false)
    public int getStatus() {
        return this.status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    @Column(name = "clinical_interventions", nullable = false)
    public Integer getClinicalInterventions() {
		return clinicalInterventions;
	}

	public void setClinicalInterventions(Integer clinicalInterbentions) {
		this.clinicalInterventions = clinicalInterbentions;
	}

	@Column(name = "community_interventions", nullable = false)
	public Integer getCommunityInterventions() {
		return communityInterventions;
	}

	public void setCommunityInterventions(Integer communityInterventions) {
		this.communityInterventions = communityInterventions;
	}

	@Column(name = "created_by", nullable = false)
    public int getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_created", nullable = false, length = 19)
    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Column(name = "updated_by")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_updated", length = 19)
    public Date getDateUpdated() {
        return this.dateUpdated;
    }

    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

    @Column(name = "offline_id", length = 45)
    public String getOfflineId() {
        return this.offlineId;
    }

    public void setOfflineId(String offlineId) {
        this.offlineId = offlineId;
    }

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "beneficiaries")
    public Set<VulnerabilityHistory> getVulnerabilityHistories() {
        return this.vulnerabilityHistories;
    }

    public void setVulnerabilityHistories(Set<VulnerabilityHistory> vulnerabilityHistories) {
        this.vulnerabilityHistories = vulnerabilityHistories;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "beneficiaries")
    @JsonIgnore
    public Set<BeneficiariesInterventions> getBeneficiariesInterventionses() {
        return this.beneficiariesInterventionses;
    }

    public void setBeneficiariesInterventionses(Set<BeneficiariesInterventions> beneficiariesInterventionses) {
        this.beneficiariesInterventionses = beneficiariesInterventionses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "beneficiaries")
    @JsonIgnore
    public Set<References> getReferenceses() {
        return this.referenceses;
    }

    public void setReferenceses(Set<References> referenceses) {
        this.referenceses = referenceses;
    }

	@Column(name = "completion_status")
    public int getCompletionStatus() {
		return completionStatus;
	}

	public void setCompletionStatus(int completionStatus) {
		this.completionStatus = completionStatus;
	}

    public ObjectNode toObjectNode(String lastPulledAt) {
        ObjectMapper mapper = new ObjectMapper().registerModule(new JavaTimeModule())
                                                .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
        mapper.setSerializationInclusion(Include.NON_NULL);
        //mapper.configOverride(Map.class).setInclude(Value.construct(JsonInclude.Include.NON_NULL, JsonInclude.Include.NON_NULL));  
        
        ObjectNode beneficiary = mapper.createObjectNode();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        DateFormat shortDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        //String nullValue = null;

        if (offlineId != null) {
            beneficiary.put("id", offlineId);
        } else {
            beneficiary.put("id", id);
        }
        
        if (dateUpdated == null || dateUpdated.compareTo(dateCreated) >= 0 || lastPulledAt == null || lastPulledAt.equals("null")) {
			beneficiary.put("nui", nui);
			beneficiary.put("name", name);
			beneficiary.put("surname", surname);
			beneficiary.put("nick_name", nickName);
			beneficiary.put("organization_id", partners == null ? null : partners.getId());
			beneficiary.put("date_of_birth", dateOfBirth == null ? null : shortDateFormat.format(dateOfBirth));
			beneficiary.put("date_created", dateCreated == null ? null : dateFormat.format(dateCreated));
			beneficiary.put("date_updated", dateUpdated == null ? null : dateFormat.format(dateUpdated));
			beneficiary.put("gender", String.valueOf(gender));
			beneficiary.put("address", address);
			beneficiary.put("phone_number", phoneNumber);
			beneficiary.put("e_mail", EMail);
			beneficiary.put("enrollment_date", enrollmentDate != null ? shortDateFormat.format(enrollmentDate) : null);
            beneficiary.put("via", via);
            beneficiary.put("partner_id", String.valueOf(partnerId));
            beneficiary.put("nationality", nationality);
            beneficiary.put("entry_point", entryPoint);
			if (neighborhood == null) {
				beneficiary.put("neighborhood_id", "");
				beneficiary.put("locality_id", "");
				beneficiary.put("locality_name", "");
			} else {
				beneficiary.put("neighborhood_id", neighborhood.getId());
				if (locality == null) {
					beneficiary.put("locality_id", "");
					beneficiary.put("locality_name", "");
					
				} else {
					beneficiary.put("locality_id", locality.getId());
					beneficiary.put("locality_name", locality.getName());
				}
			}
			beneficiary.put("district_id", district.getId());
			beneficiary.put("district_code", district.getCode());
			beneficiary.put("province_id", district.getProvince().getId());
            beneficiary.put("us_id", us == null ? null : us.getId());
            if(vbltLivesWith != null) beneficiary.put("vblt_lives_with", vbltLivesWith);
            if(vbltIsOrphan != null) beneficiary.put("vblt_is_orphan", vbltIsOrphan);
            if(vbltIsStudent != null) beneficiary.put("vblt_is_student", vbltIsStudent);
            if(vbltSchoolGrade != null) beneficiary.put("vblt_school_grade", vbltSchoolGrade);
            if(vbltSchoolName != null) beneficiary.put("vblt_school_name", vbltSchoolName);
            if(vbltIsDeficient != null) beneficiary.put("vblt_is_deficient", vbltIsDeficient);
            if(vbltDeficiencyType != null) beneficiary.put("vblt_deficiency_type", vbltDeficiencyType);
            if(vbltMarriedBefore != null) beneficiary.put("vblt_married_before", vbltMarriedBefore);
            if(vbltPregnantBefore != null) beneficiary.put("vblt_pregnant_before", vbltPregnantBefore);
            if(vbltChildren != null) beneficiary.put("vblt_children", vbltChildren);
            if(vbltPregnantOrBreastfeeding != null) beneficiary.put("vblt_pregnant_or_breastfeeding", vbltPregnantOrBreastfeeding);
            if(vbltIsEmployed != null) beneficiary.put("vblt_is_employed", vbltIsEmployed);
            if(vbltIdp != null) beneficiary.put("vblt_idp", vbltIdp);
            if(vbltTestedHiv != null) beneficiary.put("vblt_tested_hiv", vbltTestedHiv);
            if(vbltSexuallyActive != null) beneficiary.put("vblt_sexually_active", vbltSexuallyActive);
            if(vbltPregnantOrHasChildren != null) beneficiary.put("vblt_pregnant_or_has_children", vbltPregnantOrHasChildren);
            if(vbltMultiplePartners != null) beneficiary.put("vblt_multiple_partners", vbltMultiplePartners);
            if(vbltIsMigrant != null) beneficiary.put("vblt_is_migrant", vbltIsMigrant);
            if(vbltTraffickingVictim != null) beneficiary.put("vblt_trafficking_victim", vbltTraffickingVictim);
            if(vbltSexualExploitation != null) beneficiary.put("vblt_sexual_exploitation", vbltSexualExploitation);
            if(vbltSexploitationTime != null) beneficiary.put("vblt_sexploitation_time", vbltSexploitationTime);
            if(vbltVbgVictim != null) beneficiary.put("vblt_vbg_victim", vbltVbgVictim);
            if(vbltVbgType != null) beneficiary.put("vblt_vbg_type", vbltVbgType);
            if(vbltVbgTime != null) beneficiary.put("vblt_vbg_time", vbltVbgTime);
            if(vbltAlcoholDrugsUse != null) beneficiary.put("vblt_alcohol_drugs_use", vbltAlcoholDrugsUse);
            if(vbltStiHistory != null) beneficiary.put("vblt_sti_history", vbltStiHistory);
            if(vbltSexWorker != null) beneficiary.put("vblt_sex_worker", vbltSexWorker);
            if(vbltHouseSustainer != null) beneficiary.put("vblt_house_sustainer", vbltHouseSustainer);
            beneficiary.put("status", status);
            
            int[] ids = referenceses.stream()
                    .mapToInt(References::getId)
                    .toArray();
       
            beneficiary.put("references_a", Arrays.toString(ids));
            beneficiary.put("online_id", id); // flag to control if entity is synchronized with the backend
            beneficiary.put("offline_id", offlineId);
        } else { // ensure online_id is updated first
            beneficiary.put("online_id", id);
        }
        return beneficiary;
    }

    public void update(BeneficiarySyncModel model, String timestamp) {
        this.offlineId = model.getId();
        this.nui = model.getNui();
        this.name = model.getName();
        this.surname = model.getSurname();
        this.nickName = model.getNick_name();
        this.partners = model.getOrganization_id() == 0 ? null : new Partners(model.getOrganization_id());
        this.dateOfBirth = model.getDate_of_birth();
        this.dateCreated = model.getDate_created();
        this.dateUpdated = model.getDate_updated();
        this.gender = model.getGender();
        this.address = model.getAddress();
        this.phoneNumber = model.getPhone_number();
        this.EMail = model.getE_mail();
        this.enrollmentDate = model.getEnrollment_date();
        this.via = model.getVia();
        this.nationality = model.getNationality();
        this.entryPoint = model.getEntry_point();
        this.neighborhood = model.getNeighborhood_id() == 0 ? null : new Neighborhood(model.getNeighborhood_id());
        this.us = model.getUs_id() == 0? null : new Us(model.getUs_id());
        this.status = Integer.valueOf(model.getStatus());
        this.vbltLivesWith = model.getVblt_lives_with();
        this.vbltIsOrphan = model.getVblt_is_orphan();
        this.vbltIsStudent = model.getVblt_is_student();
        this.vbltSchoolGrade = model.getVblt_school_grade();
        this.vbltSchoolName = model.getVblt_school_name();
        this.vbltIsDeficient = model.getVblt_is_deficient();
        this.vbltDeficiencyType = model.getVblt_deficiency_type();
        this.vbltMarriedBefore = model.getVblt_married_before();
        this.vbltPregnantBefore = model.getVblt_pregnant_before();
        this.vbltChildren = model.getVblt_children();
        this.vbltPregnantOrBreastfeeding = model.getVblt_pregnant_or_breastfeeding();
        this.vbltIsEmployed = model.getVblt_is_employed();
        this.vbltIdp = model.getVblt_idp();
        this.vbltTestedHiv = model.getVblt_tested_hiv();
        this.vbltSexuallyActive = model.getVblt_sexually_active();
        this.vbltPregnantOrHasChildren = model.getVblt_pregnant_or_has_children();
        this.vbltMultiplePartners = model.getVblt_multiple_partners();
        this.vbltIsMigrant = model.getVblt_is_migrant();
        this.vbltTraffickingVictim = model.getVblt_trafficking_victim();
        this.vbltSexualExploitation = model.getVblt_sexual_exploitation();
        this.vbltSexploitationTime = model.getVblt_sexploitation_time();
        this.vbltVbgVictim = model.getVblt_vbg_victim();
        this.vbltVbgType = model.getVblt_vbg_type();
        this.vbltVbgTime = model.getVblt_vbg_time();
        this.vbltAlcoholDrugsUse = model.getVblt_alcohol_drugs_use();
        this.vbltStiHistory = model.getVblt_sti_history();
        this.vbltSexWorker = model.getVblt_sex_worker();
        this.vbltHouseSustainer = model.getVblt_house_sustainer();
    }
    
    public void fill(ObjectNode obj, String field, Object value) {
    	if(value == null) {
    		return;
    	}
    	
    	if(value instanceof String) {
    		obj.put(field, (String)value);
    	}
    	if(value instanceof Byte) {
    		obj.put(field, (Byte)value);
    	}
    	if(value instanceof Double) {
    		obj.put(field, (Double)value);
    	}
    	if(value instanceof Integer) {
    		obj.put(field, (Integer)value);
    	}
    	if(value instanceof Float) {
    		obj.put(field, (Float)value);
    	}
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Beneficiaries other = (Beneficiaries) obj;
		if (!id.equals(other.id))
			return false;
		return true;
	}

}
