package dlt.dltbackendmaster.domain;
// Generated Jun 13, 2022, 9:37:47 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CurriculumsServicesId generated by hbm2java
 */
@Embeddable
public class CurriculumsServicesId implements java.io.Serializable {

	private static final long serialVersionUID = -6017925144258424300L;
	private int curriculumId;
	private int serviceId;

	public CurriculumsServicesId() {
	}

	public CurriculumsServicesId(int curriculumId, int serviceId) {
		this.curriculumId = curriculumId;
		this.serviceId = serviceId;
	}

	@Column(name = "curriculum_id", nullable = false)
	public int getCurriculumId() {
		return this.curriculumId;
	}

	public void setCurriculumId(int curriculumId) {
		this.curriculumId = curriculumId;
	}

	@Column(name = "service_id", nullable = false)
	public int getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(int serviceId) {
		this.serviceId = serviceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CurriculumsServicesId))
			return false;
		CurriculumsServicesId castOther = (CurriculumsServicesId) other;

		return (this.getCurriculumId() == castOther.getCurriculumId())
				&& (this.getServiceId() == castOther.getServiceId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCurriculumId();
		result = 37 * result + this.getServiceId();
		return result;
	}

}
