package dlt.dltbackendmaster.domain;
// Generated Nov 9, 2021, 8:12:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HsHrDistrict generated by hbm2java
 */
@Entity
@Table(name = "hs_hr_district", catalog = "dreamsco")
public class HsHrDistrict implements java.io.Serializable {

	private Integer districtCode;
	private String codDistrito;
	private String districtName;
	private String provinceCode;

	public HsHrDistrict() {
	}

	public HsHrDistrict(String codDistrito, String districtName) {
		this.codDistrito = codDistrito;
		this.districtName = districtName;
	}

	public HsHrDistrict(String codDistrito, String districtName, String provinceCode) {
		this.codDistrito = codDistrito;
		this.districtName = districtName;
		this.provinceCode = provinceCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "district_code", unique = true, nullable = false)
	public Integer getDistrictCode() {
		return this.districtCode;
	}

	public void setDistrictCode(Integer districtCode) {
		this.districtCode = districtCode;
	}

	@Column(name = "cod_distrito", nullable = false, length = 10)
	public String getCodDistrito() {
		return this.codDistrito;
	}

	public void setCodDistrito(String codDistrito) {
		this.codDistrito = codDistrito;
	}

	@Column(name = "district_name", nullable = false, length = 50)
	public String getDistrictName() {
		return this.districtName;
	}

	public void setDistrictName(String districtName) {
		this.districtName = districtName;
	}

	@Column(name = "province_code", length = 13)
	public String getProvinceCode() {
		return this.provinceCode;
	}

	public void setProvinceCode(String provinceCode) {
		this.provinceCode = provinceCode;
	}

}
