package dlt.dltbackendmaster.domain;
// Generated Nov 9, 2021, 8:12:12 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HsHrEmployee generated by hbm2java
 */
@Entity
@Table(name = "hs_hr_employee", catalog = "dreamsco")
public class HsHrEmployee implements java.io.Serializable {

	private Integer id;
	private int empNumber;
	private String memberId;
	private String empLastname;
	private String empFirstname;
	private String empMiddleName;
	private String empNickName;
	private int pontoEntrada;
	private Integer parceiroId;
	private Integer parceiroBenificiarioId;
	private Integer via;
	private Integer idadeAnos;
	private Integer idadeActual;
	private Integer estudante;
	private Integer estudanteClasse;
	private String estudanteEscola;
	private Integer gravida;
	private Integer filhos;
	private Integer bairroId;
	private String encarregadoEducacao;
	private Integer deficiencia;
	private String deficienciaTipo;
	private Integer houseSustainer;
	private Integer marriedBefore;
	private Integer pregantOrBreastfeed;
	private Integer employed;
	private Integer testedHiv;
	private Integer vbgExploracaoSexual;
	private Integer vbgVsexTempo;
	private Integer vbgMigranteTrafico;
	private String vbgVitimaTrafico;
	private Integer vbgSexualActiva;
	private Integer vbgRelacaoMultipla;
	private Integer vbgVitima;
	private String vbgTipoViolencia;
	private Integer vbgTempo;
	private String counCode;
	private String provinCode;
	private String districtCode;
	private String cityCode;
	private Integer membroLocalidadeId;
	private Integer usId;
	private Integer membroZona;
	private Integer membroCirculo;
	private Integer membroCelula;
	private String membroDataAdmissao;
	private String membroCarataoEleitor;
	private String membroCargoPartidoId;
	private Short empSmoker;
	private String ethnicRaceCode;
	private String empBirthday;
	private Integer nationCode;
	private Short empGender;
	private String empMaritalStatus;
	private String empSsnNum;
	private String empSinNum;
	private String empOtherId;
	private String empDriLiceNum;
	private Date empDriLiceExpDate;
	private String empMilitaryService;
	private Integer empStatus;
	private Integer jobTitleCode;
	private Integer eeoCatCode;
	private Integer workStation;
	private String empStreet1;
	private String empStreet2;
	private String empZipcode;
	private String empHmTelephone;
	private String empMobile;
	private String empWorkTelephone;
	private String empWorkEmail;
	private String salGrdCode;
	private Date joinedDate;
	private String empOthEmail;
	private Integer terminationId;
	private Integer vbgSexWorker;
	private String bi;
	private String nuit;
	private String passaporte;
	private String dire;
	private String biDataI;
	private String biDataF;
	private String custom3;
	private String otherProfInfo;
	private String nuitDataI;
	private String nuitDataF;
	private String custom7;
	private String custom8;
	private String custom9;
	private String custom10;
	private Integer criadoPor;
	private Integer actualizadoPor;
	private Date criadoEm;
	private Date actualizadoEm;
	private String userLocation;
	private String userLocation2;
	private Integer flagVulneravel;
	private Integer vulnerabilidade;
	private Integer alcoholDrugsUse;
	private Integer stiHistory;

	public HsHrEmployee() {
	}

	public HsHrEmployee(int empNumber, String empLastname, String empFirstname, String empMiddleName, int pontoEntrada,
			String districtCode) {
		this.empNumber = empNumber;
		this.empLastname = empLastname;
		this.empFirstname = empFirstname;
		this.empMiddleName = empMiddleName;
		this.pontoEntrada = pontoEntrada;
		this.districtCode = districtCode;
	}

	public HsHrEmployee(int empNumber, String memberId, String empLastname, String empFirstname, String empMiddleName,
			String empNickName, int pontoEntrada, Integer parceiroId, Integer parceiroBenificiarioId, Integer via,
			Integer idadeAnos, Integer idadeActual, Integer estudante, Integer estudanteClasse, String estudanteEscola,
			Integer gravida, Integer filhos, Integer bairroId, String encarregadoEducacao, Integer deficiencia,
			String deficienciaTipo, Integer houseSustainer, Integer marriedBefore, Integer pregantOrBreastfeed,
			Integer employed, Integer testedHiv, Integer vbgExploracaoSexual, Integer vbgVsexTempo,
			Integer vbgMigranteTrafico, String vbgVitimaTrafico, Integer vbgSexualActiva, Integer vbgRelacaoMultipla,
			Integer vbgVitima, String vbgTipoViolencia, Integer vbgTempo, String counCode, String provinCode,
			String districtCode, String cityCode, Integer membroLocalidadeId, Integer usId, Integer membroZona,
			Integer membroCirculo, Integer membroCelula, String membroDataAdmissao, String membroCarataoEleitor,
			String membroCargoPartidoId, Short empSmoker, String ethnicRaceCode, String empBirthday, Integer nationCode,
			Short empGender, String empMaritalStatus, String empSsnNum, String empSinNum, String empOtherId,
			String empDriLiceNum, Date empDriLiceExpDate, String empMilitaryService, Integer empStatus,
			Integer jobTitleCode, Integer eeoCatCode, Integer workStation, String empStreet1, String empStreet2,
			String empZipcode, String empHmTelephone, String empMobile, String empWorkTelephone, String empWorkEmail,
			String salGrdCode, Date joinedDate, String empOthEmail, Integer terminationId, Integer vbgSexWorker,
			String bi, String nuit, String passaporte, String dire, String biDataI, String biDataF, String custom3,
			String otherProfInfo, String nuitDataI, String nuitDataF, String custom7, String custom8, String custom9,
			String custom10, Integer criadoPor, Integer actualizadoPor, Date criadoEm, Date actualizadoEm,
			String userLocation, String userLocation2, Integer flagVulneravel, Integer vulnerabilidade,
			Integer alcoholDrugsUse, Integer stiHistory) {
		this.empNumber = empNumber;
		this.memberId = memberId;
		this.empLastname = empLastname;
		this.empFirstname = empFirstname;
		this.empMiddleName = empMiddleName;
		this.empNickName = empNickName;
		this.pontoEntrada = pontoEntrada;
		this.parceiroId = parceiroId;
		this.parceiroBenificiarioId = parceiroBenificiarioId;
		this.via = via;
		this.idadeAnos = idadeAnos;
		this.idadeActual = idadeActual;
		this.estudante = estudante;
		this.estudanteClasse = estudanteClasse;
		this.estudanteEscola = estudanteEscola;
		this.gravida = gravida;
		this.filhos = filhos;
		this.bairroId = bairroId;
		this.encarregadoEducacao = encarregadoEducacao;
		this.deficiencia = deficiencia;
		this.deficienciaTipo = deficienciaTipo;
		this.houseSustainer = houseSustainer;
		this.marriedBefore = marriedBefore;
		this.pregantOrBreastfeed = pregantOrBreastfeed;
		this.employed = employed;
		this.testedHiv = testedHiv;
		this.vbgExploracaoSexual = vbgExploracaoSexual;
		this.vbgVsexTempo = vbgVsexTempo;
		this.vbgMigranteTrafico = vbgMigranteTrafico;
		this.vbgVitimaTrafico = vbgVitimaTrafico;
		this.vbgSexualActiva = vbgSexualActiva;
		this.vbgRelacaoMultipla = vbgRelacaoMultipla;
		this.vbgVitima = vbgVitima;
		this.vbgTipoViolencia = vbgTipoViolencia;
		this.vbgTempo = vbgTempo;
		this.counCode = counCode;
		this.provinCode = provinCode;
		this.districtCode = districtCode;
		this.cityCode = cityCode;
		this.membroLocalidadeId = membroLocalidadeId;
		this.usId = usId;
		this.membroZona = membroZona;
		this.membroCirculo = membroCirculo;
		this.membroCelula = membroCelula;
		this.membroDataAdmissao = membroDataAdmissao;
		this.membroCarataoEleitor = membroCarataoEleitor;
		this.membroCargoPartidoId = membroCargoPartidoId;
		this.empSmoker = empSmoker;
		this.ethnicRaceCode = ethnicRaceCode;
		this.empBirthday = empBirthday;
		this.nationCode = nationCode;
		this.empGender = empGender;
		this.empMaritalStatus = empMaritalStatus;
		this.empSsnNum = empSsnNum;
		this.empSinNum = empSinNum;
		this.empOtherId = empOtherId;
		this.empDriLiceNum = empDriLiceNum;
		this.empDriLiceExpDate = empDriLiceExpDate;
		this.empMilitaryService = empMilitaryService;
		this.empStatus = empStatus;
		this.jobTitleCode = jobTitleCode;
		this.eeoCatCode = eeoCatCode;
		this.workStation = workStation;
		this.empStreet1 = empStreet1;
		this.empStreet2 = empStreet2;
		this.empZipcode = empZipcode;
		this.empHmTelephone = empHmTelephone;
		this.empMobile = empMobile;
		this.empWorkTelephone = empWorkTelephone;
		this.empWorkEmail = empWorkEmail;
		this.salGrdCode = salGrdCode;
		this.joinedDate = joinedDate;
		this.empOthEmail = empOthEmail;
		this.terminationId = terminationId;
		this.vbgSexWorker = vbgSexWorker;
		this.bi = bi;
		this.nuit = nuit;
		this.passaporte = passaporte;
		this.dire = dire;
		this.biDataI = biDataI;
		this.biDataF = biDataF;
		this.custom3 = custom3;
		this.otherProfInfo = otherProfInfo;
		this.nuitDataI = nuitDataI;
		this.nuitDataF = nuitDataF;
		this.custom7 = custom7;
		this.custom8 = custom8;
		this.custom9 = custom9;
		this.custom10 = custom10;
		this.criadoPor = criadoPor;
		this.actualizadoPor = actualizadoPor;
		this.criadoEm = criadoEm;
		this.actualizadoEm = actualizadoEm;
		this.userLocation = userLocation;
		this.userLocation2 = userLocation2;
		this.flagVulneravel = flagVulneravel;
		this.vulnerabilidade = vulnerabilidade;
		this.alcoholDrugsUse = alcoholDrugsUse;
		this.stiHistory = stiHistory;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "emp_number", nullable = false)
	public int getEmpNumber() {
		return this.empNumber;
	}

	public void setEmpNumber(int empNumber) {
		this.empNumber = empNumber;
	}

	@Column(name = "member_id", length = 50)
	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	@Column(name = "emp_lastname", nullable = false, length = 100)
	public String getEmpLastname() {
		return this.empLastname;
	}

	public void setEmpLastname(String empLastname) {
		this.empLastname = empLastname;
	}

	@Column(name = "emp_firstname", nullable = false, length = 100)
	public String getEmpFirstname() {
		return this.empFirstname;
	}

	public void setEmpFirstname(String empFirstname) {
		this.empFirstname = empFirstname;
	}

	@Column(name = "emp_middle_name", nullable = false, length = 100)
	public String getEmpMiddleName() {
		return this.empMiddleName;
	}

	public void setEmpMiddleName(String empMiddleName) {
		this.empMiddleName = empMiddleName;
	}

	@Column(name = "emp_nick_name", length = 100)
	public String getEmpNickName() {
		return this.empNickName;
	}

	public void setEmpNickName(String empNickName) {
		this.empNickName = empNickName;
	}

	@Column(name = "ponto_entrada", nullable = false)
	public int getPontoEntrada() {
		return this.pontoEntrada;
	}

	public void setPontoEntrada(int pontoEntrada) {
		this.pontoEntrada = pontoEntrada;
	}

	@Column(name = "parceiro_id")
	public Integer getParceiroId() {
		return this.parceiroId;
	}

	public void setParceiroId(Integer parceiroId) {
		this.parceiroId = parceiroId;
	}

	@Column(name = "parceiro_benificiario_id")
	public Integer getParceiroBenificiarioId() {
		return this.parceiroBenificiarioId;
	}

	public void setParceiroBenificiarioId(Integer parceiroBenificiarioId) {
		this.parceiroBenificiarioId = parceiroBenificiarioId;
	}

	@Column(name = "via")
	public Integer getVia() {
		return this.via;
	}

	public void setVia(Integer via) {
		this.via = via;
	}

	@Column(name = "idade_anos")
	public Integer getIdadeAnos() {
		return this.idadeAnos;
	}

	public void setIdadeAnos(Integer idadeAnos) {
		this.idadeAnos = idadeAnos;
	}

	@Column(name = "idade_actual")
	public Integer getIdadeActual() {
		return this.idadeActual;
	}

	public void setIdadeActual(Integer idadeActual) {
		this.idadeActual = idadeActual;
	}

	@Column(name = "estudante")
	public Integer getEstudante() {
		return this.estudante;
	}

	public void setEstudante(Integer estudante) {
		this.estudante = estudante;
	}

	@Column(name = "estudante_classe")
	public Integer getEstudanteClasse() {
		return this.estudanteClasse;
	}

	public void setEstudanteClasse(Integer estudanteClasse) {
		this.estudanteClasse = estudanteClasse;
	}

	@Column(name = "estudante_escola", length = 150)
	public String getEstudanteEscola() {
		return this.estudanteEscola;
	}

	public void setEstudanteEscola(String estudanteEscola) {
		this.estudanteEscola = estudanteEscola;
	}

	@Column(name = "gravida")
	public Integer getGravida() {
		return this.gravida;
	}

	public void setGravida(Integer gravida) {
		this.gravida = gravida;
	}

	@Column(name = "filhos")
	public Integer getFilhos() {
		return this.filhos;
	}

	public void setFilhos(Integer filhos) {
		this.filhos = filhos;
	}

	@Column(name = "bairro_id")
	public Integer getBairroId() {
		return this.bairroId;
	}

	public void setBairroId(Integer bairroId) {
		this.bairroId = bairroId;
	}

	@Column(name = "encarregado_educacao", length = 150)
	public String getEncarregadoEducacao() {
		return this.encarregadoEducacao;
	}

	public void setEncarregadoEducacao(String encarregadoEducacao) {
		this.encarregadoEducacao = encarregadoEducacao;
	}

	@Column(name = "deficiencia")
	public Integer getDeficiencia() {
		return this.deficiencia;
	}

	public void setDeficiencia(Integer deficiencia) {
		this.deficiencia = deficiencia;
	}

	@Column(name = "deficiencia_tipo", length = 250)
	public String getDeficienciaTipo() {
		return this.deficienciaTipo;
	}

	public void setDeficienciaTipo(String deficienciaTipo) {
		this.deficienciaTipo = deficienciaTipo;
	}

	@Column(name = "house_sustainer")
	public Integer getHouseSustainer() {
		return this.houseSustainer;
	}

	public void setHouseSustainer(Integer houseSustainer) {
		this.houseSustainer = houseSustainer;
	}

	@Column(name = "married_before")
	public Integer getMarriedBefore() {
		return this.marriedBefore;
	}

	public void setMarriedBefore(Integer marriedBefore) {
		this.marriedBefore = marriedBefore;
	}

	@Column(name = "pregant_or_breastfeed")
	public Integer getPregantOrBreastfeed() {
		return this.pregantOrBreastfeed;
	}

	public void setPregantOrBreastfeed(Integer pregantOrBreastfeed) {
		this.pregantOrBreastfeed = pregantOrBreastfeed;
	}

	@Column(name = "employed")
	public Integer getEmployed() {
		return this.employed;
	}

	public void setEmployed(Integer employed) {
		this.employed = employed;
	}

	@Column(name = "tested_hiv")
	public Integer getTestedHiv() {
		return this.testedHiv;
	}

	public void setTestedHiv(Integer testedHiv) {
		this.testedHiv = testedHiv;
	}

	@Column(name = "vbg_exploracao_sexual")
	public Integer getVbgExploracaoSexual() {
		return this.vbgExploracaoSexual;
	}

	public void setVbgExploracaoSexual(Integer vbgExploracaoSexual) {
		this.vbgExploracaoSexual = vbgExploracaoSexual;
	}

	@Column(name = "vbg_vsex_tempo")
	public Integer getVbgVsexTempo() {
		return this.vbgVsexTempo;
	}

	public void setVbgVsexTempo(Integer vbgVsexTempo) {
		this.vbgVsexTempo = vbgVsexTempo;
	}

	@Column(name = "vbg_migrante_trafico")
	public Integer getVbgMigranteTrafico() {
		return this.vbgMigranteTrafico;
	}

	public void setVbgMigranteTrafico(Integer vbgMigranteTrafico) {
		this.vbgMigranteTrafico = vbgMigranteTrafico;
	}

	@Column(name = "vbg_vitima_trafico", length = 10)
	public String getVbgVitimaTrafico() {
		return this.vbgVitimaTrafico;
	}

	public void setVbgVitimaTrafico(String vbgVitimaTrafico) {
		this.vbgVitimaTrafico = vbgVitimaTrafico;
	}

	@Column(name = "vbg_sexual_activa")
	public Integer getVbgSexualActiva() {
		return this.vbgSexualActiva;
	}

	public void setVbgSexualActiva(Integer vbgSexualActiva) {
		this.vbgSexualActiva = vbgSexualActiva;
	}

	@Column(name = "vbg_relacao_multipla")
	public Integer getVbgRelacaoMultipla() {
		return this.vbgRelacaoMultipla;
	}

	public void setVbgRelacaoMultipla(Integer vbgRelacaoMultipla) {
		this.vbgRelacaoMultipla = vbgRelacaoMultipla;
	}

	@Column(name = "vbg_vitima")
	public Integer getVbgVitima() {
		return this.vbgVitima;
	}

	public void setVbgVitima(Integer vbgVitima) {
		this.vbgVitima = vbgVitima;
	}

	@Column(name = "vbg_tipo_violencia", length = 200)
	public String getVbgTipoViolencia() {
		return this.vbgTipoViolencia;
	}

	public void setVbgTipoViolencia(String vbgTipoViolencia) {
		this.vbgTipoViolencia = vbgTipoViolencia;
	}

	@Column(name = "vbg_tempo")
	public Integer getVbgTempo() {
		return this.vbgTempo;
	}

	public void setVbgTempo(Integer vbgTempo) {
		this.vbgTempo = vbgTempo;
	}

	@Column(name = "coun_code", length = 100)
	public String getCounCode() {
		return this.counCode;
	}

	public void setCounCode(String counCode) {
		this.counCode = counCode;
	}

	@Column(name = "provin_code", length = 100)
	public String getProvinCode() {
		return this.provinCode;
	}

	public void setProvinCode(String provinCode) {
		this.provinCode = provinCode;
	}

	@Column(name = "district_code", nullable = false, length = 100)
	public String getDistrictCode() {
		return this.districtCode;
	}

	public void setDistrictCode(String districtCode) {
		this.districtCode = districtCode;
	}

	@Column(name = "city_code", length = 100)
	public String getCityCode() {
		return this.cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	@Column(name = "membro_localidade_id")
	public Integer getMembroLocalidadeId() {
		return this.membroLocalidadeId;
	}

	public void setMembroLocalidadeId(Integer membroLocalidadeId) {
		this.membroLocalidadeId = membroLocalidadeId;
	}

	@Column(name = "us_id")
	public Integer getUsId() {
		return this.usId;
	}

	public void setUsId(Integer usId) {
		this.usId = usId;
	}

	@Column(name = "membro_zona")
	public Integer getMembroZona() {
		return this.membroZona;
	}

	public void setMembroZona(Integer membroZona) {
		this.membroZona = membroZona;
	}

	@Column(name = "membro_circulo")
	public Integer getMembroCirculo() {
		return this.membroCirculo;
	}

	public void setMembroCirculo(Integer membroCirculo) {
		this.membroCirculo = membroCirculo;
	}

	@Column(name = "membro_celula")
	public Integer getMembroCelula() {
		return this.membroCelula;
	}

	public void setMembroCelula(Integer membroCelula) {
		this.membroCelula = membroCelula;
	}

	@Column(name = "membro_data_admissao", length = 20)
	public String getMembroDataAdmissao() {
		return this.membroDataAdmissao;
	}

	public void setMembroDataAdmissao(String membroDataAdmissao) {
		this.membroDataAdmissao = membroDataAdmissao;
	}

	@Column(name = "membro_caratao_eleitor", length = 50)
	public String getMembroCarataoEleitor() {
		return this.membroCarataoEleitor;
	}

	public void setMembroCarataoEleitor(String membroCarataoEleitor) {
		this.membroCarataoEleitor = membroCarataoEleitor;
	}

	@Column(name = "membro_cargo_partido_id", length = 50)
	public String getMembroCargoPartidoId() {
		return this.membroCargoPartidoId;
	}

	public void setMembroCargoPartidoId(String membroCargoPartidoId) {
		this.membroCargoPartidoId = membroCargoPartidoId;
	}

	@Column(name = "emp_smoker")
	public Short getEmpSmoker() {
		return this.empSmoker;
	}

	public void setEmpSmoker(Short empSmoker) {
		this.empSmoker = empSmoker;
	}

	@Column(name = "ethnic_race_code", length = 13)
	public String getEthnicRaceCode() {
		return this.ethnicRaceCode;
	}

	public void setEthnicRaceCode(String ethnicRaceCode) {
		this.ethnicRaceCode = ethnicRaceCode;
	}

	@Column(name = "emp_birthday", length = 50)
	public String getEmpBirthday() {
		return this.empBirthday;
	}

	public void setEmpBirthday(String empBirthday) {
		this.empBirthday = empBirthday;
	}

	@Column(name = "nation_code")
	public Integer getNationCode() {
		return this.nationCode;
	}

	public void setNationCode(Integer nationCode) {
		this.nationCode = nationCode;
	}

	@Column(name = "emp_gender")
	public Short getEmpGender() {
		return this.empGender;
	}

	public void setEmpGender(Short empGender) {
		this.empGender = empGender;
	}

	@Column(name = "emp_marital_status", length = 20)
	public String getEmpMaritalStatus() {
		return this.empMaritalStatus;
	}

	public void setEmpMaritalStatus(String empMaritalStatus) {
		this.empMaritalStatus = empMaritalStatus;
	}

	@Column(name = "emp_ssn_num", length = 100)
	public String getEmpSsnNum() {
		return this.empSsnNum;
	}

	public void setEmpSsnNum(String empSsnNum) {
		this.empSsnNum = empSsnNum;
	}

	@Column(name = "emp_sin_num", length = 100)
	public String getEmpSinNum() {
		return this.empSinNum;
	}

	public void setEmpSinNum(String empSinNum) {
		this.empSinNum = empSinNum;
	}

	@Column(name = "emp_other_id", length = 100)
	public String getEmpOtherId() {
		return this.empOtherId;
	}

	public void setEmpOtherId(String empOtherId) {
		this.empOtherId = empOtherId;
	}

	@Column(name = "emp_dri_lice_num", length = 100)
	public String getEmpDriLiceNum() {
		return this.empDriLiceNum;
	}

	public void setEmpDriLiceNum(String empDriLiceNum) {
		this.empDriLiceNum = empDriLiceNum;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "emp_dri_lice_exp_date", length = 10)
	public Date getEmpDriLiceExpDate() {
		return this.empDriLiceExpDate;
	}

	public void setEmpDriLiceExpDate(Date empDriLiceExpDate) {
		this.empDriLiceExpDate = empDriLiceExpDate;
	}

	@Column(name = "emp_military_service", length = 100)
	public String getEmpMilitaryService() {
		return this.empMilitaryService;
	}

	public void setEmpMilitaryService(String empMilitaryService) {
		this.empMilitaryService = empMilitaryService;
	}

	@Column(name = "emp_status")
	public Integer getEmpStatus() {
		return this.empStatus;
	}

	public void setEmpStatus(Integer empStatus) {
		this.empStatus = empStatus;
	}

	@Column(name = "job_title_code")
	public Integer getJobTitleCode() {
		return this.jobTitleCode;
	}

	public void setJobTitleCode(Integer jobTitleCode) {
		this.jobTitleCode = jobTitleCode;
	}

	@Column(name = "eeo_cat_code")
	public Integer getEeoCatCode() {
		return this.eeoCatCode;
	}

	public void setEeoCatCode(Integer eeoCatCode) {
		this.eeoCatCode = eeoCatCode;
	}

	@Column(name = "work_station")
	public Integer getWorkStation() {
		return this.workStation;
	}

	public void setWorkStation(Integer workStation) {
		this.workStation = workStation;
	}

	@Column(name = "emp_street1", length = 100)
	public String getEmpStreet1() {
		return this.empStreet1;
	}

	public void setEmpStreet1(String empStreet1) {
		this.empStreet1 = empStreet1;
	}

	@Column(name = "emp_street2", length = 100)
	public String getEmpStreet2() {
		return this.empStreet2;
	}

	public void setEmpStreet2(String empStreet2) {
		this.empStreet2 = empStreet2;
	}

	@Column(name = "emp_zipcode", length = 20)
	public String getEmpZipcode() {
		return this.empZipcode;
	}

	public void setEmpZipcode(String empZipcode) {
		this.empZipcode = empZipcode;
	}

	@Column(name = "emp_hm_telephone", length = 50)
	public String getEmpHmTelephone() {
		return this.empHmTelephone;
	}

	public void setEmpHmTelephone(String empHmTelephone) {
		this.empHmTelephone = empHmTelephone;
	}

	@Column(name = "emp_mobile", length = 50)
	public String getEmpMobile() {
		return this.empMobile;
	}

	public void setEmpMobile(String empMobile) {
		this.empMobile = empMobile;
	}

	@Column(name = "emp_work_telephone", length = 50)
	public String getEmpWorkTelephone() {
		return this.empWorkTelephone;
	}

	public void setEmpWorkTelephone(String empWorkTelephone) {
		this.empWorkTelephone = empWorkTelephone;
	}

	@Column(name = "emp_work_email", length = 50)
	public String getEmpWorkEmail() {
		return this.empWorkEmail;
	}

	public void setEmpWorkEmail(String empWorkEmail) {
		this.empWorkEmail = empWorkEmail;
	}

	@Column(name = "sal_grd_code", length = 13)
	public String getSalGrdCode() {
		return this.salGrdCode;
	}

	public void setSalGrdCode(String salGrdCode) {
		this.salGrdCode = salGrdCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "joined_date", length = 10)
	public Date getJoinedDate() {
		return this.joinedDate;
	}

	public void setJoinedDate(Date joinedDate) {
		this.joinedDate = joinedDate;
	}

	@Column(name = "emp_oth_email", length = 50)
	public String getEmpOthEmail() {
		return this.empOthEmail;
	}

	public void setEmpOthEmail(String empOthEmail) {
		this.empOthEmail = empOthEmail;
	}

	@Column(name = "termination_id")
	public Integer getTerminationId() {
		return this.terminationId;
	}

	public void setTerminationId(Integer terminationId) {
		this.terminationId = terminationId;
	}

	@Column(name = "vbg_sex_worker")
	public Integer getVbgSexWorker() {
		return this.vbgSexWorker;
	}

	public void setVbgSexWorker(Integer vbgSexWorker) {
		this.vbgSexWorker = vbgSexWorker;
	}

	@Column(name = "bi", length = 15)
	public String getBi() {
		return this.bi;
	}

	public void setBi(String bi) {
		this.bi = bi;
	}

	@Column(name = "nuit", length = 15)
	public String getNuit() {
		return this.nuit;
	}

	public void setNuit(String nuit) {
		this.nuit = nuit;
	}

	@Column(name = "passaporte", length = 15)
	public String getPassaporte() {
		return this.passaporte;
	}

	public void setPassaporte(String passaporte) {
		this.passaporte = passaporte;
	}

	@Column(name = "dire", length = 15)
	public String getDire() {
		return this.dire;
	}

	public void setDire(String dire) {
		this.dire = dire;
	}

	@Column(name = "bi_data_i", length = 50)
	public String getBiDataI() {
		return this.biDataI;
	}

	public void setBiDataI(String biDataI) {
		this.biDataI = biDataI;
	}

	@Column(name = "bi_data_f", length = 50)
	public String getBiDataF() {
		return this.biDataF;
	}

	public void setBiDataF(String biDataF) {
		this.biDataF = biDataF;
	}

	@Column(name = "custom3", length = 250)
	public String getCustom3() {
		return this.custom3;
	}

	public void setCustom3(String custom3) {
		this.custom3 = custom3;
	}

	@Column(name = "other_prof_info", length = 250)
	public String getOtherProfInfo() {
		return this.otherProfInfo;
	}

	public void setOtherProfInfo(String otherProfInfo) {
		this.otherProfInfo = otherProfInfo;
	}

	@Column(name = "nuit_data_i", length = 50)
	public String getNuitDataI() {
		return this.nuitDataI;
	}

	public void setNuitDataI(String nuitDataI) {
		this.nuitDataI = nuitDataI;
	}

	@Column(name = "nuit_data_f", length = 50)
	public String getNuitDataF() {
		return this.nuitDataF;
	}

	public void setNuitDataF(String nuitDataF) {
		this.nuitDataF = nuitDataF;
	}

	@Column(name = "custom7", length = 250)
	public String getCustom7() {
		return this.custom7;
	}

	public void setCustom7(String custom7) {
		this.custom7 = custom7;
	}

	@Column(name = "custom8", length = 250)
	public String getCustom8() {
		return this.custom8;
	}

	public void setCustom8(String custom8) {
		this.custom8 = custom8;
	}

	@Column(name = "custom9", length = 250)
	public String getCustom9() {
		return this.custom9;
	}

	public void setCustom9(String custom9) {
		this.custom9 = custom9;
	}

	@Column(name = "custom10", length = 250)
	public String getCustom10() {
		return this.custom10;
	}

	public void setCustom10(String custom10) {
		this.custom10 = custom10;
	}

	@Column(name = "criado_por")
	public Integer getCriadoPor() {
		return this.criadoPor;
	}

	public void setCriadoPor(Integer criadoPor) {
		this.criadoPor = criadoPor;
	}

	@Column(name = "actualizado_por")
	public Integer getActualizadoPor() {
		return this.actualizadoPor;
	}

	public void setActualizadoPor(Integer actualizadoPor) {
		this.actualizadoPor = actualizadoPor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "criado_em", length = 19)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "actualizado_em", length = 19)
	public Date getActualizadoEm() {
		return this.actualizadoEm;
	}

	public void setActualizadoEm(Date actualizadoEm) {
		this.actualizadoEm = actualizadoEm;
	}

	@Column(name = "user_location", length = 50)
	public String getUserLocation() {
		return this.userLocation;
	}

	public void setUserLocation(String userLocation) {
		this.userLocation = userLocation;
	}

	@Column(name = "user_location2", length = 200)
	public String getUserLocation2() {
		return this.userLocation2;
	}

	public void setUserLocation2(String userLocation2) {
		this.userLocation2 = userLocation2;
	}

	@Column(name = "flag_vulneravel")
	public Integer getFlagVulneravel() {
		return this.flagVulneravel;
	}

	public void setFlagVulneravel(Integer flagVulneravel) {
		this.flagVulneravel = flagVulneravel;
	}

	@Column(name = "vulnerabilidade")
	public Integer getVulnerabilidade() {
		return this.vulnerabilidade;
	}

	public void setVulnerabilidade(Integer vulnerabilidade) {
		this.vulnerabilidade = vulnerabilidade;
	}

	@Column(name = "alcohol_drugs_use")
	public Integer getAlcoholDrugsUse() {
		return this.alcoholDrugsUse;
	}

	public void setAlcoholDrugsUse(Integer alcoholDrugsUse) {
		this.alcoholDrugsUse = alcoholDrugsUse;
	}

	@Column(name = "sti_history")
	public Integer getStiHistory() {
		return this.stiHistory;
	}

	public void setStiHistory(Integer stiHistory) {
		this.stiHistory = stiHistory;
	}

}
