package dlt.dltbackendmaster.domain;
// Generated Nov 9, 2021, 8:12:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HsHrCountry generated by hbm2java
 */
@Entity
@Table(name = "hs_hr_country", catalog = "dreamsco")
public class HsHrCountry implements java.io.Serializable {

	private String couCode;
	private String name;
	private String couName;
	private String iso3;
	private Short numcode;

	public HsHrCountry() {
	}

	public HsHrCountry(String couCode, String name, String couName) {
		this.couCode = couCode;
		this.name = name;
		this.couName = couName;
	}

	public HsHrCountry(String couCode, String name, String couName, String iso3, Short numcode) {
		this.couCode = couCode;
		this.name = name;
		this.couName = couName;
		this.iso3 = iso3;
		this.numcode = numcode;
	}

	@Id

	@Column(name = "cou_code", unique = true, nullable = false, length = 2)
	public String getCouCode() {
		return this.couCode;
	}

	public void setCouCode(String couCode) {
		this.couCode = couCode;
	}

	@Column(name = "name", nullable = false, length = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "cou_name", nullable = false, length = 80)
	public String getCouName() {
		return this.couName;
	}

	public void setCouName(String couName) {
		this.couName = couName;
	}

	@Column(name = "iso3", length = 3)
	public String getIso3() {
		return this.iso3;
	}

	public void setIso3(String iso3) {
		this.iso3 = iso3;
	}

	@Column(name = "numcode")
	public Short getNumcode() {
		return this.numcode;
	}

	public void setNumcode(Short numcode) {
		this.numcode = numcode;
	}

}
