package dlt.dltbackendmaster.domain;
// Generated Jan 16, 2022, 11:30:32 PM by Hibernate Tools 5.4.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PartnerType generated by hbm2java
 */
public class PartnerType implements java.io.Serializable {

	private int id;
	private User userByCreatedBy;
	private User userByUpdatedBy;
	private String name;
	private String description;
	private int status;
	private Date dateCreated;
	private Date dateUpdated;
	private Set partners = new HashSet(0);

	public PartnerType() {
	}

	public PartnerType(int id, User userByCreatedBy, String name, int status, Date dateCreated) {
		this.id = id;
		this.userByCreatedBy = userByCreatedBy;
		this.name = name;
		this.status = status;
		this.dateCreated = dateCreated;
	}

	public PartnerType(int id, User userByCreatedBy, User userByUpdatedBy, String name, String description, int status,
			Date dateCreated, Date dateUpdated, Set partners) {
		this.id = id;
		this.userByCreatedBy = userByCreatedBy;
		this.userByUpdatedBy = userByUpdatedBy;
		this.name = name;
		this.description = description;
		this.status = status;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
		this.partners = partners;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUserByCreatedBy() {
		return this.userByCreatedBy;
	}

	public void setUserByCreatedBy(User userByCreatedBy) {
		this.userByCreatedBy = userByCreatedBy;
	}

	public User getUserByUpdatedBy() {
		return this.userByUpdatedBy;
	}

	public void setUserByUpdatedBy(User userByUpdatedBy) {
		this.userByUpdatedBy = userByUpdatedBy;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	public Set getPartners() {
		return this.partners;
	}

	public void setPartners(Set partners) {
		this.partners = partners;
	}

}
