package dlt.dltbackendmaster.domain;
// Generated Jan 16, 2022, 11:30:32 PM by Hibernate Tools 5.4.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Profile generated by hbm2java
 */
public class Profile implements java.io.Serializable {

	private int id;
	private User userByUpdatedBy;
	private User userByCreatedBy;
	private String name;
	private String descriptiom;
	private int status;
	private Date dateCreated;
	private Date dateUpdated;
	private Set users = new HashSet(0);

	public Profile() {
	}

	public Profile(int id, User userByCreatedBy, String name, int status, Date dateCreated) {
		this.id = id;
		this.userByCreatedBy = userByCreatedBy;
		this.name = name;
		this.status = status;
		this.dateCreated = dateCreated;
	}

	public Profile(int id, User userByUpdatedBy, User userByCreatedBy, String name, String descriptiom, int status,
			Date dateCreated, Date dateUpdated, Set users) {
		this.id = id;
		this.userByUpdatedBy = userByUpdatedBy;
		this.userByCreatedBy = userByCreatedBy;
		this.name = name;
		this.descriptiom = descriptiom;
		this.status = status;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
		this.users = users;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUserByUpdatedBy() {
		return this.userByUpdatedBy;
	}

	public void setUserByUpdatedBy(User userByUpdatedBy) {
		this.userByUpdatedBy = userByUpdatedBy;
	}

	public User getUserByCreatedBy() {
		return this.userByCreatedBy;
	}

	public void setUserByCreatedBy(User userByCreatedBy) {
		this.userByCreatedBy = userByCreatedBy;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescriptiom() {
		return this.descriptiom;
	}

	public void setDescriptiom(String descriptiom) {
		this.descriptiom = descriptiom;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
