package dlt.dltbackendmaster.domain;
// Generated Jan 16, 2022, 11:30:32 PM by Hibernate Tools 5.4.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Province generated by hbm2java
 */
public class Province implements java.io.Serializable {

	private int id;
	private User userByUpdatedBy;
	private User userByCreatedBy;
	private String code;
	private String name;
	private int status;
	private Date createDate;
	private Date updateDate;
	private Set districts = new HashSet(0);

	public Province() {
	}

	public Province(int id, User userByCreatedBy, String code, String name, int status, Date createDate) {
		this.id = id;
		this.userByCreatedBy = userByCreatedBy;
		this.code = code;
		this.name = name;
		this.status = status;
		this.createDate = createDate;
	}

	public Province(int id, User userByUpdatedBy, User userByCreatedBy, String code, String name, int status,
			Date createDate, Date updateDate, Set districts) {
		this.id = id;
		this.userByUpdatedBy = userByUpdatedBy;
		this.userByCreatedBy = userByCreatedBy;
		this.code = code;
		this.name = name;
		this.status = status;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.districts = districts;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUserByUpdatedBy() {
		return this.userByUpdatedBy;
	}

	public void setUserByUpdatedBy(User userByUpdatedBy) {
		this.userByUpdatedBy = userByUpdatedBy;
	}

	public User getUserByCreatedBy() {
		return this.userByCreatedBy;
	}

	public void setUserByCreatedBy(User userByCreatedBy) {
		this.userByCreatedBy = userByCreatedBy;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Set getDistricts() {
		return this.districts;
	}

	public void setDistricts(Set districts) {
		this.districts = districts;
	}

}
