package dlt.dltbackendmaster.domain;
// Generated Nov 9, 2021, 8:12:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Token generated by hbm2java
 */
@Entity
@Table(name = "token", catalog = "dreamsco")
public class Token implements java.io.Serializable {

	private TokenId id;

	public Token() {
	}

	public Token(TokenId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "code", column = @Column(name = "code", nullable = false, length = 50)),
			@AttributeOverride(name = "createdAt", column = @Column(name = "created_at", nullable = false)),
			@AttributeOverride(name = "type", column = @Column(name = "type", nullable = false)) })
	public TokenId getId() {
		return this.id;
	}

	public void setId(TokenId id) {
		this.id = id;
	}

}
