package dlt.dltbackendmaster.domain;
// Generated Nov 9, 2021, 8:12:12 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TokenId generated by hbm2java
 */
@Embeddable
public class TokenId implements java.io.Serializable {

	private int userId;
	private String code;
	private int createdAt;
	private short type;

	public TokenId() {
	}

	public TokenId(int userId, String code, int createdAt, short type) {
		this.userId = userId;
		this.code = code;
		this.createdAt = createdAt;
		this.type = type;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "code", nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "created_at", nullable = false)
	public int getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(int createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "type", nullable = false)
	public short getType() {
		return this.type;
	}

	public void setType(short type) {
		this.type = type;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TokenId))
			return false;
		TokenId castOther = (TokenId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getCode() == castOther.getCode()) || (this.getCode() != null && castOther.getCode() != null
						&& this.getCode().equals(castOther.getCode())))
				&& (this.getCreatedAt() == castOther.getCreatedAt()) && (this.getType() == castOther.getType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + (getCode() == null ? 0 : this.getCode().hashCode());
		result = 37 * result + this.getCreatedAt();
		result = 37 * result + this.getType();
		return result;
	}

}
