package dlt.dltbackendmaster.domain;
// Generated Jan 16, 2022, 11:30:32 PM by Hibernate Tools 5.4.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Us generated by hbm2java
 */
public class Us implements java.io.Serializable {

	private int id;
	private UsType usType;
	private User userByCreatedBy;
	private User userByUpdatedBy;
	private String code;
	private String name;
	private String description;
	private Float latitude;
	private Float longitude;
	private int localityId;
	private int status;
	private Date dateCreated;
	private Date dateUpdated;
	private Set users = new HashSet(0);

	public Us() {
	}

	public Us(int id, UsType usType, User userByCreatedBy, String code, String name, int localityId, int status,
			Date dateCreated) {
		this.id = id;
		this.usType = usType;
		this.userByCreatedBy = userByCreatedBy;
		this.code = code;
		this.name = name;
		this.localityId = localityId;
		this.status = status;
		this.dateCreated = dateCreated;
	}

	public Us(int id, UsType usType, User userByCreatedBy, User userByUpdatedBy, String code, String name,
			String description, Float latitude, Float longitude, int localityId, int status, Date dateCreated,
			Date dateUpdated, Set users) {
		this.id = id;
		this.usType = usType;
		this.userByCreatedBy = userByCreatedBy;
		this.userByUpdatedBy = userByUpdatedBy;
		this.code = code;
		this.name = name;
		this.description = description;
		this.latitude = latitude;
		this.longitude = longitude;
		this.localityId = localityId;
		this.status = status;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
		this.users = users;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public UsType getUsType() {
		return this.usType;
	}

	public void setUsType(UsType usType) {
		this.usType = usType;
	}

	public User getUserByCreatedBy() {
		return this.userByCreatedBy;
	}

	public void setUserByCreatedBy(User userByCreatedBy) {
		this.userByCreatedBy = userByCreatedBy;
	}

	public User getUserByUpdatedBy() {
		return this.userByUpdatedBy;
	}

	public void setUserByUpdatedBy(User userByUpdatedBy) {
		this.userByUpdatedBy = userByUpdatedBy;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Float getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	public Float getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Float longitude) {
		this.longitude = longitude;
	}

	public int getLocalityId() {
		return this.localityId;
	}

	public void setLocalityId(int localityId) {
		this.localityId = localityId;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
