package dlt.dltbackendmaster.domain;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import dlt.dltbackendmaster.domain.watermelondb.UserDetailsSyncModel;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "user_details", catalog = "dreams_db")
@NamedQueries({
		@NamedQuery(name = "UserDetails.findByUserId", query = "SELECT u FROM UserDetails u where u.userId = :userId") })
public class UserDetails implements java.io.Serializable {
	private static final long serialVersionUID = -411480320058856740L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@Column(name = "districts", length = 255)
	private String districts;

	@Column(name = "provinces", length = 255)
	private String provinces;

	@Column(name = "localities", length = 255)
	private String localities;

	@Column(name = "uss", length = 255)
	private String uss;

	@Column(name = "user_id", length = 255)
	private String userId;

	@Column(name = "last_login_date", length = 255)
	private String lastLoginDate;

	@Column(name = "password_last_change_date", length = 255)
	private String passwordLastChangeDate;

	@Column(name = "profile_id", length = 255)
	private String profileId;

	@Column(name = "entry_point", length = 255)
	private String entryPoint;

	@Column(name = "partner_id", length = 255)
	private String partnerId;

	@Column(name = "next_clean_date", length = 255)
	private String nextCleanDate;

	@Column(name = "was_cleaned", length = 255)
	private String wasCleaned;

	public UserDetails() {
	}

	public UserDetails(String districts, String provinces, String localities, String uss, String userId,
			String lastLoginDate, String passwordLastChangeDate, String profileId, String entryPoint, String partnerId,
			String nextCleanDate, String wasCleaned) {
		super();
		this.districts = districts;
		this.provinces = provinces;
		this.localities = localities;
		this.uss = uss;
		this.userId = userId;
		this.lastLoginDate = lastLoginDate;
		this.passwordLastChangeDate = passwordLastChangeDate;
		this.profileId = profileId;
		this.entryPoint = entryPoint;
		this.partnerId = partnerId;
		this.nextCleanDate = nextCleanDate;
		this.wasCleaned = wasCleaned;
	}

	public UserDetails(UserDetailsSyncModel model, String timestamp) {
		this.districts = model.getDistricts();
		this.provinces = model.getProvinces();
		this.localities = model.getLocalities();
		this.uss = model.getUss();
		this.userId = model.getUser_id();
		this.lastLoginDate = model.getLast_login_date();
		this.passwordLastChangeDate = model.getPassword_last_change_date();
		this.profileId = model.getProfile_id();
		this.entryPoint = model.getEntry_point();
		this.partnerId = model.getPartner_id();
		this.nextCleanDate = model.getNext_clean_date();
		this.wasCleaned = model.getWas_cleaned();
	}

	public String getDistricts() {
		return districts;
	}

	public void setDistricts(String districts) {
		this.districts = districts;
	}

	public String getProvinces() {
		return provinces;
	}

	public void setProvinces(String provinces) {
		this.provinces = provinces;
	}

	public String getLocalities() {
		return localities;
	}

	public void setLocalities(String localities) {
		this.localities = localities;
	}

	public String getUss() {
		return uss;
	}

	public void setUss(String uss) {
		this.uss = uss;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getLastLoginDate() {
		return lastLoginDate;
	}

	public void setLastLoginDate(String lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	public String getPasswordLastChangeDate() {
		return passwordLastChangeDate;
	}

	public void setPasswordLastChangeDate(String passwordLastChangeDate) {
		this.passwordLastChangeDate = passwordLastChangeDate;
	}

	public String getProfileId() {
		return profileId;
	}

	public void setProfileId(String profileId) {
		this.profileId = profileId;
	}

	public String getEntryPoint() {
		return entryPoint;
	}

	public void setEntryPoint(String entryPoint) {
		this.entryPoint = entryPoint;
	}

	public String getPartnerId() {
		return partnerId;
	}

	public void setPartnerId(String partnerId) {
		this.partnerId = partnerId;
	}

	public String getNextCleanDate() {
		return nextCleanDate;
	}

	public void setNextCleanDate(String nextCleanDate) {
		this.nextCleanDate = nextCleanDate;
	}

	public String getWasCleaned() {
		return wasCleaned;
	}

	public void setWasCleaned(String wasCleaned) {
		this.wasCleaned = wasCleaned;
	}

	public void update(UserDetailsSyncModel model, String timestamp) {
		this.districts = model.getDistricts();
		this.provinces = model.getProvinces();
		this.localities = model.getLocalities();
		this.uss = model.getUss();
		this.userId = model.getUser_id();
		this.lastLoginDate = model.getLast_login_date();
		this.passwordLastChangeDate = model.getPassword_last_change_date();
		this.profileId = model.getProfile_id();
		this.entryPoint = model.getEntry_point();
		this.partnerId = model.getPartner_id();
		this.nextCleanDate = model.getNext_clean_date();
		this.wasCleaned = model.getWas_cleaned();
	}
}
