package dlt.dltbackendmaster.domain;
// Generated Jan 16, 2022, 11:30:32 PM by Hibernate Tools 5.4.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UsType generated by hbm2java
 */
public class UsType implements java.io.Serializable {

	private int id;
	private User userByUpdatedBy;
	private User userByCreatedBy;
	private String name;
	private String level;
	private String type;
	private String description;
	private int status;
	private Date dateCreated;
	private Date dateUpdated;
	private Set uses = new HashSet(0);

	public UsType() {
	}

	public UsType(int id, User userByCreatedBy, String name, String level, String type, int status, Date dateCreated) {
		this.id = id;
		this.userByCreatedBy = userByCreatedBy;
		this.name = name;
		this.level = level;
		this.type = type;
		this.status = status;
		this.dateCreated = dateCreated;
	}

	public UsType(int id, User userByUpdatedBy, User userByCreatedBy, String name, String level, String type,
			String description, int status, Date dateCreated, Date dateUpdated, Set uses) {
		this.id = id;
		this.userByUpdatedBy = userByUpdatedBy;
		this.userByCreatedBy = userByCreatedBy;
		this.name = name;
		this.level = level;
		this.type = type;
		this.description = description;
		this.status = status;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
		this.uses = uses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUserByUpdatedBy() {
		return this.userByUpdatedBy;
	}

	public void setUserByUpdatedBy(User userByUpdatedBy) {
		this.userByUpdatedBy = userByUpdatedBy;
	}

	public User getUserByCreatedBy() {
		return this.userByCreatedBy;
	}

	public void setUserByCreatedBy(User userByCreatedBy) {
		this.userByCreatedBy = userByCreatedBy;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	public Set getUses() {
		return this.uses;
	}

	public void setUses(Set uses) {
		this.uses = uses;
	}

}
